from __future__ import annotations

import base64
import binascii
import json
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb


SCHEMA = """
CREATE TABLE IF NOT EXISTS device_state (
    user_id TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, vendor, product)
);

CREATE TABLE IF NOT EXISTS dives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    dive_uid TEXT NOT NULL,
    started_at TEXT,
    duration_seconds INTEGER,
    max_depth_m DOUBLE PRECISION,
    avg_depth_m DOUBLE PRECISION,
    fields_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_sha256 TEXT NOT NULL,
    raw_data BYTEA NOT NULL,
    samples_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    imported_at TEXT NOT NULL
);
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def init_db(conn: psycopg.Connection) -> None:
    with conn.cursor() as cur:
        cur.execute(SCHEMA)
        cur.execute("ALTER TABLE device_state ADD COLUMN IF NOT EXISTS user_id TEXT")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS user_id TEXT")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS fields_json JSONB NOT NULL DEFAULT '{}'::jsonb")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS samples_json JSONB NOT NULL DEFAULT '[]'::jsonb")
        cur.execute("UPDATE device_state SET user_id='legacy' WHERE user_id IS NULL")
        cur.execute("UPDATE dives SET user_id='legacy' WHERE user_id IS NULL")
        cur.execute("ALTER TABLE device_state ALTER COLUMN user_id SET NOT NULL")
        cur.execute("ALTER TABLE dives ALTER COLUMN user_id SET NOT NULL")
        cur.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'device_state'::regclass
                      AND conname = 'device_state_pkey'
                ) THEN
                    ALTER TABLE device_state DROP CONSTRAINT device_state_pkey;
                END IF;
            END $$;
            """
        )
        cur.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'device_state'::regclass
                      AND conname = 'device_state_pkey'
                ) THEN
                    ALTER TABLE device_state
                    ADD CONSTRAINT device_state_pkey PRIMARY KEY (user_id, vendor, product);
                END IF;
            END $$;
            """
        )
        cur.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'dives'::regclass
                      AND conname = 'dives_dive_uid_key'
                ) THEN
                    ALTER TABLE dives DROP CONSTRAINT dives_dive_uid_key;
                END IF;
            END $$;
            """
        )
        cur.execute("DROP INDEX IF EXISTS idx_dives_started_at")
        cur.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_dives_user_dive_uid ON dives (user_id, dive_uid)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_dives_user_started_at ON dives (user_id, started_at DESC, id DESC)")
    conn.commit()


def open_db(database_url: str) -> psycopg.Connection:
    conn = psycopg.connect(database_url, row_factory=dict_row)
    init_db(conn)
    return conn


def decode_dive_row(row: dict, include_samples: bool, include_raw_data: bool) -> dict:
    fields = row.get("fields_json") or {}
    samples = row.get("samples_json") or []
    raw_data = row.get("raw_data")

    payload = {
        "id": row["id"],
        "vendor": row["vendor"],
        "product": row["product"],
        "fingerprint_hex": row.get("fingerprint_hex"),
        "dive_uid": row["dive_uid"],
        "started_at": row.get("started_at"),
        "duration_seconds": row.get("duration_seconds"),
        "max_depth_m": row.get("max_depth_m"),
        "avg_depth_m": row.get("avg_depth_m"),
        "fields": fields if isinstance(fields, dict) else json.loads(fields),
        "raw_sha256": row["raw_sha256"],
        "raw_data_size": len(raw_data) if raw_data is not None else 0,
        "imported_at": row["imported_at"],
    }

    if isinstance(samples, str):
        samples = json.loads(samples)
    payload["sample_count"] = len(samples)
    if include_samples:
        payload["samples"] = samples
    if include_raw_data and raw_data is not None:
        payload["raw_data_b64"] = base64.b64encode(raw_data).decode("ascii")
    return payload


def insert_dive_record(conn: psycopg.Connection, user_id: str, payload: dict) -> bool:
    imported_at = payload.get("imported_at") or now_iso()
    fields = payload.get("fields") or {}
    samples = payload.get("samples") or []
    raw_data = decode_base64_payload(payload)

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO dives(
                user_id, vendor, product, fingerprint_hex, dive_uid, started_at,
                duration_seconds, max_depth_m, avg_depth_m, fields_json,
                raw_sha256, raw_data, samples_json, imported_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, dive_uid) DO NOTHING
            RETURNING id
            """,
            (
                user_id,
                payload["vendor"],
                payload["product"],
                payload.get("fingerprint_hex"),
                payload["dive_uid"],
                payload.get("started_at"),
                payload.get("duration_seconds"),
                payload.get("max_depth_m"),
                payload.get("avg_depth_m"),
                Jsonb(fields),
                payload["raw_sha256"],
                raw_data,
                Jsonb(samples),
                imported_at,
            ),
        )
        inserted = cur.fetchone() is not None
    conn.commit()
    return inserted


def get_dive_id_by_uid(conn: psycopg.Connection, user_id: str, dive_uid: str) -> int | None:
    with conn.cursor() as cur:
        cur.execute("SELECT id FROM dives WHERE user_id=%s AND dive_uid=%s", (user_id, dive_uid))
        row = cur.fetchone()
    return row["id"] if row else None


def save_device_state(conn: psycopg.Connection, user_id: str, vendor: str, product: str, fingerprint_hex: str | None) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO device_state(user_id, vendor, product, fingerprint_hex, updated_at)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (user_id, vendor, product)
            DO UPDATE SET fingerprint_hex=excluded.fingerprint_hex, updated_at=excluded.updated_at
            """,
            (user_id, vendor, product, fingerprint_hex, now_iso()),
        )
    conn.commit()


def get_device_state(conn: psycopg.Connection, user_id: str, vendor: str, product: str) -> dict:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT vendor, product, fingerprint_hex, updated_at
            FROM device_state
            WHERE user_id=%s AND vendor=%s AND product=%s
            """,
            (user_id, vendor, product),
        )
        row = cur.fetchone()
    if not row:
        return {
            "vendor": vendor,
            "product": product,
            "fingerprint_hex": None,
            "updated_at": None,
        }
    return row


def list_dives(
    conn: psycopg.Connection,
    user_id: str,
    include_samples: bool,
    include_raw_data: bool,
    limit: int,
    offset: int,
) -> tuple[list[dict], int]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT *
            FROM dives
            WHERE user_id=%s
            ORDER BY started_at DESC, id DESC
            LIMIT %s OFFSET %s
            """,
            (user_id, limit, offset),
        )
        rows = cur.fetchall()
        cur.execute("SELECT COUNT(*) AS total FROM dives WHERE user_id=%s", (user_id,))
        total = cur.fetchone()["total"]
    dives = [decode_dive_row(row, include_samples, include_raw_data) for row in rows]
    return dives, total


def summarize_dives(dives: list[dict], total_count: int | None = None) -> dict:
    def pressure_range(dive: dict) -> tuple[float | None, float | None]:
        tanks = dive.get("fields", {}).get("tanks") if isinstance(dive.get("fields"), dict) else []
        primary_tank = tanks[0] if isinstance(tanks, list) and tanks else {}
        if isinstance(primary_tank, dict):
            begin = primary_tank.get("beginpressure_bar")
            end = primary_tank.get("endpressure_bar")
            if isinstance(begin, (int, float)) and isinstance(end, (int, float)):
                return float(begin), float(end)

        pressures: list[float] = []
        for sample in dive.get("samples") or []:
            tank_pressure = sample.get("tank_pressure_bar") if isinstance(sample, dict) else None
            if isinstance(tank_pressure, dict):
                numeric_values = [value for value in tank_pressure.values() if isinstance(value, (int, float))]
                if numeric_values:
                    pressures.append(float(numeric_values[0]))
        if not pressures:
            return None, None
        return max(pressures), min(pressures)

    total_dives = int(total_count if total_count is not None else len(dives))
    total_seconds = sum(int(dive.get("duration_seconds") or 0) for dive in dives)
    max_depth = max((float(dive.get("max_depth_m") or 0) for dive in dives), default=0.0)
    total_bar_consumed = 0
    for dive in dives:
        begin, end = pressure_range(dive)
        if begin is None or end is None:
            continue
        total_bar_consumed += max(0, round(begin - end))
    average_duration_seconds = round(total_seconds / total_dives, 2) if total_dives else 0
    average_max_depth_m = (
        round(
            sum(float(dive.get("max_depth_m") or 0) for dive in dives) / total_dives,
            2,
        )
        if total_dives
        else 0
    )
    total_hours = round(total_seconds / 3600, 1) if total_seconds else 0

    return {
        "totalDives": total_dives,
        "totalSeconds": total_seconds,
        "totalHours": total_hours,
        "maxDepth": max_depth,
        "totalBarConsumed": total_bar_consumed,
        "averageDurationSeconds": average_duration_seconds,
        "averageMaxDepth": average_max_depth_m,
        "bottomTimeProgress": min(100, round(total_hours)),
    }


def get_dive(conn: psycopg.Connection, user_id: str, dive_id: int, include_raw_data: bool) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM dives WHERE user_id=%s AND id=%s", (user_id, dive_id))
        row = cur.fetchone()
    return decode_dive_row(row, include_samples=True, include_raw_data=include_raw_data) if row else None


def sanitize_logbook_payload(payload: dict | None) -> dict:
    source = payload or {}
    if isinstance(source.get("logbook"), dict):
        source = source["logbook"]
    commit = bool((payload or {}).get("commit"))

    def clean_text(key: str) -> str:
        value = source.get(key, "")
        return value.strip() if isinstance(value, str) else ""

    logbook = {
        "site": clean_text("site"),
        "buddy": clean_text("buddy"),
        "guide": clean_text("guide"),
        "notes": clean_text("notes"),
        "updated_at": now_iso(),
    }

    required = ("site", "buddy", "guide")
    if commit and all(logbook[key] for key in required):
        logbook["status"] = "complete"
        existing_completed_at = source.get("completed_at")
        logbook["completed_at"] = existing_completed_at if isinstance(existing_completed_at, str) and existing_completed_at else now_iso()
    else:
        logbook["status"] = "pending"

    return logbook


def update_dive_logbook(conn: psycopg.Connection, user_id: str, dive_id: int, payload: dict | None) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM dives WHERE user_id=%s AND id=%s", (user_id, dive_id))
        row = cur.fetchone()
        if not row:
            return None

        fields = row.get("fields_json") or {}
        if not isinstance(fields, dict):
            fields = json.loads(fields)
        fields["logbook"] = sanitize_logbook_payload(payload)

        cur.execute(
            "UPDATE dives SET fields_json=%s WHERE user_id=%s AND id=%s",
            (Jsonb(fields), user_id, dive_id),
        )
    conn.commit()
    return get_dive(conn, user_id, dive_id, include_raw_data=False)


def import_sqlite_device_state(conn: psycopg.Connection, rows: list[dict], *, user_id: str = "legacy") -> int:
    if not rows:
        return 0
    with conn.cursor() as cur:
        for row in rows:
            cur.execute(
                """
                INSERT INTO device_state(user_id, vendor, product, fingerprint_hex, updated_at)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (user_id, vendor, product)
                DO UPDATE SET fingerprint_hex=excluded.fingerprint_hex, updated_at=excluded.updated_at
                """,
                (user_id, row["vendor"], row["product"], row["fingerprint_hex"], row["updated_at"]),
            )
    conn.commit()
    return len(rows)


def import_sqlite_dive_rows(conn: psycopg.Connection, rows: list[dict], *, user_id: str = "legacy") -> int:
    if not rows:
        return 0
    inserted = 0
    with conn.cursor() as cur:
        for row in rows:
            fields = row["fields_json"]
            samples = row["samples_json"]
            if isinstance(fields, str):
                fields = json.loads(fields)
            if isinstance(samples, str):
                samples = json.loads(samples)

            cur.execute(
                """
                INSERT INTO dives(
                    id, user_id, vendor, product, fingerprint_hex, dive_uid, started_at,
                    duration_seconds, max_depth_m, avg_depth_m, fields_json,
                    raw_sha256, raw_data, samples_json, imported_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (user_id, dive_uid) DO NOTHING
                RETURNING id
                """,
                (
                    row["id"],
                    user_id,
                    row["vendor"],
                    row["product"],
                    row["fingerprint_hex"],
                    row["dive_uid"],
                    row["started_at"],
                    row["duration_seconds"],
                    row["max_depth_m"],
                    row["avg_depth_m"],
                    Jsonb(fields),
                    row["raw_sha256"],
                    row["raw_data"],
                    Jsonb(samples),
                    row["imported_at"],
                ),
            )
            if cur.fetchone() is not None:
                inserted += 1

        cur.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('dives', 'id'),
                COALESCE((SELECT MAX(id) FROM dives), 1),
                true
            )
            """
        )
    conn.commit()
    return inserted


def decode_base64_payload(payload: dict) -> bytes:
    try:
        return base64.b64decode(payload["raw_data_b64"], validate=True)
    except (ValueError, binascii.Error) as exc:
        raise ValueError("raw_data_b64 must be valid base64") from exc
