from __future__ import annotations

import base64
import binascii
import json
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb


SCHEMA = """
CREATE TABLE IF NOT EXISTS device_state (
    user_id TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, vendor, product)
);

CREATE TABLE IF NOT EXISTS dives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    dive_uid TEXT NOT NULL,
    started_at TEXT,
    duration_seconds INTEGER,
    duration_ms BIGINT,
    max_depth_m DOUBLE PRECISION,
    avg_depth_m DOUBLE PRECISION,
    import_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fields_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_sha256 TEXT NOT NULL,
    raw_data BYTEA NOT NULL,
    samples_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    imported_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_profile (
    user_id TEXT PRIMARY KEY,
    name TEXT,
    email TEXT,
    licenses_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    certification TEXT,
    registry TEXT,
    license_company TEXT,
    license_certification_name TEXT,
    license_student_number TEXT,
    license_certification_date TEXT,
    license_instructor_number TEXT,
    license_pdf_name TEXT,
    license_pdf_content_type TEXT,
    license_pdf_data BYTEA,
    license_pdf_uploaded_at TEXT,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_profile_license_documents (
    user_id TEXT NOT NULL,
    license_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    pdf_data BYTEA NOT NULL,
    uploaded_at TEXT NOT NULL,
    PRIMARY KEY (user_id, license_id)
);
"""

LOGBOOK_REQUIRED_FIELDS = ("site", "buddy", "guide")
SAMPLE_TIME_UNIT_SECONDS = "seconds"
SAMPLE_TIME_UNIT_MILLISECONDS = "milliseconds"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def init_db(conn: psycopg.Connection) -> None:
    with conn.cursor() as cur:
        cur.execute(SCHEMA)
        cur.execute("ALTER TABLE device_state ADD COLUMN IF NOT EXISTS user_id TEXT")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS user_id TEXT")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS duration_ms BIGINT")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS import_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS fields_json JSONB NOT NULL DEFAULT '{}'::jsonb")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS samples_json JSONB NOT NULL DEFAULT '[]'::jsonb")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS name TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS email TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS licenses_json JSONB NOT NULL DEFAULT '[]'::jsonb")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS certification TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS registry TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_company TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_certification_name TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_student_number TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_certification_date TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_instructor_number TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_name TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_content_type TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_data BYTEA")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_uploaded_at TEXT")
        cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS updated_at TEXT")
        cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS user_id TEXT")
        cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS license_id TEXT")
        cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS filename TEXT")
        cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS content_type TEXT")
        cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS pdf_data BYTEA")
        cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS uploaded_at TEXT")
        cur.execute("UPDATE device_state SET user_id='legacy' WHERE user_id IS NULL")
        cur.execute("UPDATE dives SET user_id='legacy' WHERE user_id IS NULL")
        cur.execute("UPDATE user_profile SET updated_at=%s WHERE updated_at IS NULL", (now_iso(),))
        cur.execute(
            """
            UPDATE user_profile
            SET licenses_json = jsonb_build_array(
                jsonb_strip_nulls(
                    jsonb_build_object(
                        'company', NULLIF(BTRIM(COALESCE(license_company, '')), ''),
                        'certification_name', NULLIF(BTRIM(COALESCE(license_certification_name, certification, '')), ''),
                        'student_number', NULLIF(BTRIM(COALESCE(license_student_number, registry, '')), ''),
                        'certification_date', NULLIF(BTRIM(COALESCE(license_certification_date, '')), ''),
                        'instructor_number', NULLIF(BTRIM(COALESCE(license_instructor_number, '')), '')
                    )
                )
            )
            WHERE (licenses_json = '[]'::jsonb OR licenses_json IS NULL)
              AND (
                    NULLIF(BTRIM(COALESCE(license_company, '')), '') IS NOT NULL
                 OR NULLIF(BTRIM(COALESCE(license_certification_name, certification, '')), '') IS NOT NULL
                 OR NULLIF(BTRIM(COALESCE(license_student_number, registry, '')), '') IS NOT NULL
                 OR NULLIF(BTRIM(COALESCE(license_certification_date, '')), '') IS NOT NULL
                 OR NULLIF(BTRIM(COALESCE(license_instructor_number, '')), '') IS NOT NULL
              )
            """
        )
        cur.execute(
            """
            UPDATE dives
            SET duration_ms = duration_seconds::bigint * 1000
            WHERE duration_ms IS NULL
              AND duration_seconds IS NOT NULL
            """
        )
        cur.execute(
            """
            UPDATE dives
            SET import_payload_json = jsonb_build_object(
                'vendor', vendor,
                'product', product,
                'fingerprint_hex', fingerprint_hex,
                'dive_uid', dive_uid,
                'started_at', started_at,
                'duration_ms', duration_ms,
                'duration_seconds', CASE
                    WHEN duration_ms IS NOT NULL THEN (duration_ms / 1000)::bigint
                    ELSE duration_seconds
                END,
                'max_depth_m', max_depth_m,
                'avg_depth_m', avg_depth_m,
                'fields', COALESCE(fields_json, '{}'::jsonb),
                'raw_sha256', raw_sha256,
                'samples', COALESCE(samples_json, '[]'::jsonb),
                'imported_at', imported_at
            )
            WHERE import_payload_json = '{}'::jsonb
            """
        )
        cur.execute("UPDATE dives SET duration_seconds = NULL WHERE duration_ms IS NOT NULL")
        cur.execute("ALTER TABLE device_state ALTER COLUMN user_id SET NOT NULL")
        cur.execute("ALTER TABLE dives ALTER COLUMN user_id SET NOT NULL")
        cur.execute("ALTER TABLE user_profile ALTER COLUMN updated_at SET NOT NULL")
        cur.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'device_state'::regclass
                      AND conname = 'device_state_pkey'
                ) THEN
                    ALTER TABLE device_state DROP CONSTRAINT device_state_pkey;
                END IF;
            END $$;
            """
        )
        cur.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'device_state'::regclass
                      AND conname = 'device_state_pkey'
                ) THEN
                    ALTER TABLE device_state
                    ADD CONSTRAINT device_state_pkey PRIMARY KEY (user_id, vendor, product);
                END IF;
            END $$;
            """
        )
        cur.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'dives'::regclass
                      AND conname = 'dives_dive_uid_key'
                ) THEN
                    ALTER TABLE dives DROP CONSTRAINT dives_dive_uid_key;
                END IF;
            END $$;
            """
        )
        cur.execute("DROP INDEX IF EXISTS idx_dives_started_at")
        cur.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_dives_user_dive_uid ON dives (user_id, dive_uid)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_dives_user_started_at ON dives (user_id, started_at DESC, id DESC)")
    conn.commit()


def open_db(database_url: str) -> psycopg.Connection:
    conn = psycopg.connect(database_url, row_factory=dict_row)
    init_db(conn)
    return conn


def clean_logbook_text(value: object) -> str:
    return value.strip() if isinstance(value, str) else ""


def clean_profile_text(value: object) -> str:
    return value.strip() if isinstance(value, str) else ""


def normalize_profile_license(entry: dict | None) -> dict:
    source = entry if isinstance(entry, dict) else {}
    return {
        "id": clean_profile_text(source.get("id")),
        "company": clean_profile_text(source.get("company")),
        "certification_name": clean_profile_text(source.get("certification_name")),
        "student_number": clean_profile_text(source.get("student_number")),
        "certification_date": clean_profile_text(source.get("certification_date")),
        "instructor_number": clean_profile_text(source.get("instructor_number")),
    }


def profile_license_has_values(entry: dict | None) -> bool:
    license_entry = normalize_profile_license(entry)
    return any(value for key, value in license_entry.items() if key != "id")


def normalize_profile_licenses(entries: object) -> list[dict]:
    if not isinstance(entries, list):
        return []
    normalized: list[dict] = []
    seen_ids: set[str] = set()
    next_fallback = 1

    for entry in entries:
        if not isinstance(entry, dict):
            continue
        normalized_entry = normalize_profile_license(entry)
        if not profile_license_has_values(normalized_entry):
            continue

        license_id = normalized_entry["id"] or f"license-{next_fallback}"
        next_fallback += 1
        dedupe_suffix = 1
        base_id = license_id
        while license_id in seen_ids:
            dedupe_suffix += 1
            license_id = f"{base_id}-{dedupe_suffix}"

        normalized_entry["id"] = license_id
        seen_ids.add(license_id)
        normalized.append(normalized_entry)

    return normalized


def profile_license_document_summary(*, license_id: str, filename: str, content_type: str, data: bytes, uploaded_at: str | None) -> dict:
    return {
        "license_id": license_id,
        "filename": filename,
        "content_type": content_type,
        "size_bytes": len(data),
        "uploaded_at": uploaded_at,
        "preview_url": f"/api/profile/licenses/{license_id}/pdf",
    }


def numeric_int(value: object) -> int | None:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    return int(round(float(value)))


def duration_seconds_to_milliseconds(value: object) -> int | None:
    seconds = numeric_int(value)
    if seconds is None:
        return None
    return seconds * 1000


def duration_milliseconds_to_seconds(value: object) -> int | None:
    milliseconds = numeric_int(value)
    if milliseconds is None:
        return None
    return int(round(milliseconds / 1000))


def normalize_logbook(logbook: dict | None) -> dict:
    source = logbook if isinstance(logbook, dict) else {}
    status = "complete" if source.get("status") == "complete" else "imported"
    normalized = {
        "site": clean_logbook_text(source.get("site")),
        "buddy": clean_logbook_text(source.get("buddy")),
        "guide": clean_logbook_text(source.get("guide")),
        "notes": clean_logbook_text(source.get("notes")),
        "status": status,
    }

    updated_at = source.get("updated_at")
    if isinstance(updated_at, str) and updated_at:
        normalized["updated_at"] = updated_at

    completed_at = source.get("completed_at")
    if status == "complete" and isinstance(completed_at, str) and completed_at:
        normalized["completed_at"] = completed_at

    return normalized


def normalize_sample_time_unit(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    normalized = value.strip().lower()
    if normalized in {"s", "sec", "secs", "second", "seconds"}:
        return SAMPLE_TIME_UNIT_SECONDS
    if normalized in {"ms", "msec", "msecs", "millisecond", "milliseconds"}:
        return SAMPLE_TIME_UNIT_MILLISECONDS
    return None


def resolve_duration_milliseconds(source: dict | None) -> int | None:
    if not isinstance(source, dict):
        return None
    duration_ms = numeric_int(source.get("duration_ms"))
    if duration_ms is not None:
        return duration_ms
    return duration_seconds_to_milliseconds(source.get("duration_seconds"))


def resolve_duration_seconds(source: dict | None) -> int | None:
    duration_ms = resolve_duration_milliseconds(source)
    if duration_ms is not None:
        return duration_milliseconds_to_seconds(duration_ms)
    if not isinstance(source, dict):
        return None
    return numeric_int(source.get("duration_seconds"))


def infer_sample_time_unit(samples: list | None, duration_seconds: object) -> str | None:
    if not isinstance(samples, list):
        return None

    times = [
        sample.get("time_seconds")
        for sample in samples
        if isinstance(sample, dict) and isinstance(sample.get("time_seconds"), (int, float))
    ]
    if not times:
        return None

    duration = float(duration_seconds) if isinstance(duration_seconds, (int, float)) else 0.0
    max_time = max(times)
    if duration > 0 and max_time > duration * 5:
        return SAMPLE_TIME_UNIT_MILLISECONDS
    return SAMPLE_TIME_UNIT_SECONDS


def normalize_dive_fields(fields: dict | None, *, samples: list | None = None, duration_seconds: object = None) -> dict:
    normalized = dict(fields) if isinstance(fields, dict) else {}
    normalized["logbook"] = normalize_logbook(normalized.get("logbook"))
    sample_time_unit = normalize_sample_time_unit(normalized.get("sample_time_unit"))
    if sample_time_unit:
        normalized["sample_time_unit"] = sample_time_unit
    else:
        inferred_sample_time_unit = infer_sample_time_unit(samples, duration_seconds)
        if inferred_sample_time_unit:
            normalized["sample_time_unit"] = inferred_sample_time_unit
    return normalized


def is_logbook_complete(logbook: dict | None) -> bool:
    return normalize_logbook(logbook).get("status") == "complete"


def build_import_payload(payload: dict | None, *, imported_at: str) -> dict:
    archived = dict(payload) if isinstance(payload, dict) else {}
    archived.setdefault("imported_at", imported_at)
    duration_ms = resolve_duration_milliseconds(archived)
    if duration_ms is not None:
        archived["duration_ms"] = duration_ms
        archived.setdefault("duration_seconds", duration_milliseconds_to_seconds(duration_ms))
    archived.pop("raw_data_b64", None)
    return archived


def build_import_payload_from_row(row: dict, fields: dict, samples: list) -> dict:
    duration_ms = resolve_duration_milliseconds(row)
    return {
        "vendor": row["vendor"],
        "product": row["product"],
        "fingerprint_hex": row.get("fingerprint_hex"),
        "dive_uid": row["dive_uid"],
        "started_at": row.get("started_at"),
        "duration_ms": duration_ms,
        "duration_seconds": duration_milliseconds_to_seconds(duration_ms),
        "max_depth_m": row.get("max_depth_m"),
        "avg_depth_m": row.get("avg_depth_m"),
        "fields": fields,
        "raw_sha256": row["raw_sha256"],
        "samples": samples,
        "imported_at": row["imported_at"],
    }


def decode_dive_row(row: dict, include_samples: bool, include_raw_data: bool) -> dict:
    fields = row.get("fields_json") or {}
    samples = row.get("samples_json") or []
    raw_data = row.get("raw_data")
    duration_ms = resolve_duration_milliseconds(row)
    duration_seconds = duration_milliseconds_to_seconds(duration_ms)

    if isinstance(samples, str):
        samples = json.loads(samples)
    if not isinstance(fields, dict):
        fields = json.loads(fields)
    fields = normalize_dive_fields(fields, samples=samples, duration_seconds=duration_seconds)

    payload = {
        "id": row["id"],
        "vendor": row["vendor"],
        "product": row["product"],
        "fingerprint_hex": row.get("fingerprint_hex"),
        "dive_uid": row["dive_uid"],
        "started_at": row.get("started_at"),
        "duration_ms": duration_ms,
        "duration_seconds": duration_seconds,
        "max_depth_m": row.get("max_depth_m"),
        "avg_depth_m": row.get("avg_depth_m"),
        "fields": fields,
        "raw_sha256": row["raw_sha256"],
        "raw_data_size": len(raw_data) if raw_data is not None else 0,
        "imported_at": row["imported_at"],
    }

    payload["sample_count"] = len(samples)
    if include_samples:
        payload["samples"] = samples
    if include_raw_data and raw_data is not None:
        payload["raw_data_b64"] = base64.b64encode(raw_data).decode("ascii")
    return payload


def insert_dive_record(conn: psycopg.Connection, user_id: str, payload: dict) -> bool:
    imported_at = payload.get("imported_at") or now_iso()
    samples = payload.get("samples") or []
    duration_ms = resolve_duration_milliseconds(payload)
    duration_seconds = duration_milliseconds_to_seconds(duration_ms)
    fields = normalize_dive_fields(payload.get("fields"), samples=samples, duration_seconds=duration_seconds)
    raw_data = decode_base64_payload(payload)
    import_payload = build_import_payload(payload, imported_at=imported_at)

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO dives(
                user_id, vendor, product, fingerprint_hex, dive_uid, started_at,
                duration_seconds, duration_ms, max_depth_m, avg_depth_m, import_payload_json,
                fields_json, raw_sha256, raw_data, samples_json, imported_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, dive_uid) DO NOTHING
            RETURNING id
            """,
            (
                user_id,
                payload["vendor"],
                payload["product"],
                payload.get("fingerprint_hex"),
                payload["dive_uid"],
                payload.get("started_at"),
                None,
                duration_ms,
                payload.get("max_depth_m"),
                payload.get("avg_depth_m"),
                Jsonb(import_payload),
                Jsonb(fields),
                payload["raw_sha256"],
                raw_data,
                Jsonb(samples),
                imported_at,
            ),
        )
        inserted = cur.fetchone() is not None
    conn.commit()
    return inserted


def get_dive_id_by_uid(conn: psycopg.Connection, user_id: str, dive_uid: str) -> int | None:
    with conn.cursor() as cur:
        cur.execute("SELECT id FROM dives WHERE user_id=%s AND dive_uid=%s", (user_id, dive_uid))
        row = cur.fetchone()
    return row["id"] if row else None


def save_device_state(conn: psycopg.Connection, user_id: str, vendor: str, product: str, fingerprint_hex: str | None) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO device_state(user_id, vendor, product, fingerprint_hex, updated_at)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (user_id, vendor, product)
            DO UPDATE SET fingerprint_hex=excluded.fingerprint_hex, updated_at=excluded.updated_at
            """,
            (user_id, vendor, product, fingerprint_hex, now_iso()),
        )
    conn.commit()


def get_device_state(conn: psycopg.Connection, user_id: str, vendor: str, product: str) -> dict:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT vendor, product, fingerprint_hex, updated_at
            FROM device_state
            WHERE user_id=%s AND vendor=%s AND product=%s
            """,
            (user_id, vendor, product),
        )
        row = cur.fetchone()
    if not row:
        return {
            "vendor": vendor,
            "product": product,
            "fingerprint_hex": None,
            "updated_at": None,
        }
    return row


def list_dives(
    conn: psycopg.Connection,
    user_id: str,
    include_samples: bool,
    include_raw_data: bool,
    limit: int,
    offset: int,
) -> tuple[list[dict], int]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT *
            FROM dives
            WHERE user_id=%s
            ORDER BY started_at DESC, id DESC
            LIMIT %s OFFSET %s
            """,
            (user_id, limit, offset),
        )
        rows = cur.fetchall()
        cur.execute("SELECT COUNT(*) AS total FROM dives WHERE user_id=%s", (user_id,))
        total = cur.fetchone()["total"]
    dives = [decode_dive_row(row, include_samples, include_raw_data) for row in rows]
    return dives, total


def summarize_dives(dives: list[dict], total_count: int | None = None) -> dict:
    def pressure_range(dive: dict) -> tuple[float | None, float | None]:
        tanks = dive.get("fields", {}).get("tanks") if isinstance(dive.get("fields"), dict) else []
        primary_tank = tanks[0] if isinstance(tanks, list) and tanks else {}
        if isinstance(primary_tank, dict):
            begin = primary_tank.get("beginpressure_bar")
            end = primary_tank.get("endpressure_bar")
            if isinstance(begin, (int, float)) and isinstance(end, (int, float)):
                return float(begin), float(end)

        pressures: list[float] = []
        for sample in dive.get("samples") or []:
            tank_pressure = sample.get("tank_pressure_bar") if isinstance(sample, dict) else None
            if isinstance(tank_pressure, dict):
                numeric_values = [value for value in tank_pressure.values() if isinstance(value, (int, float))]
                if numeric_values:
                    pressures.append(float(numeric_values[0]))
        if not pressures:
            return None, None
        return max(pressures), min(pressures)

    total_dives = int(total_count if total_count is not None else len(dives))
    total_seconds = sum(int(resolve_duration_seconds(dive) or 0) for dive in dives)
    max_depth = max((float(dive.get("max_depth_m") or 0) for dive in dives), default=0.0)
    total_bar_consumed = 0
    for dive in dives:
        begin, end = pressure_range(dive)
        if begin is None or end is None:
            continue
        total_bar_consumed += max(0, round(begin - end))
    average_duration_seconds = round(total_seconds / total_dives, 2) if total_dives else 0
    average_max_depth_m = (
        round(
            sum(float(dive.get("max_depth_m") or 0) for dive in dives) / total_dives,
            2,
        )
        if total_dives
        else 0
    )
    total_hours = round(total_seconds / 3600, 1) if total_seconds else 0

    return {
        "totalDives": total_dives,
        "totalSeconds": total_seconds,
        "totalHours": total_hours,
        "maxDepth": max_depth,
        "totalBarConsumed": total_bar_consumed,
        "averageDurationSeconds": average_duration_seconds,
        "averageMaxDepth": average_max_depth_m,
        "bottomTimeProgress": min(100, round(total_hours)),
    }


def get_dive(conn: psycopg.Connection, user_id: str, dive_id: int, include_raw_data: bool) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM dives WHERE user_id=%s AND id=%s", (user_id, dive_id))
        row = cur.fetchone()
    return decode_dive_row(row, include_samples=True, include_raw_data=include_raw_data) if row else None


def empty_user_profile() -> dict:
    return {
        "name": "",
        "email": "",
        "licenses": [],
        "updated_at": None,
    }


def decode_user_profile_row(row: dict | None, license_documents: dict[str, dict] | None = None) -> dict:
    if not row:
        return empty_user_profile()

    license_documents = license_documents or {}
    licenses = row.get("licenses_json")
    if isinstance(licenses, str):
        licenses = json.loads(licenses)
    normalized_licenses = normalize_profile_licenses(licenses)
    if not normalized_licenses:
        legacy_license = normalize_profile_license(
            {
                "id": "license-1",
                "company": row.get("license_company"),
                "certification_name": row.get("license_certification_name") or row.get("certification"),
                "student_number": row.get("license_student_number") or row.get("registry"),
                "certification_date": row.get("license_certification_date"),
                "instructor_number": row.get("license_instructor_number"),
            }
        )
        if profile_license_has_values(legacy_license):
            normalized_licenses = [legacy_license]

    legacy_pdf = None
    if row.get("license_pdf_data") is not None and normalized_licenses:
        first_license_id = normalized_licenses[0]["id"]
        legacy_pdf = profile_license_document_summary(
            license_id=first_license_id,
            filename=row.get("license_pdf_name") or "diving-licenses.pdf",
            content_type=row.get("license_pdf_content_type") or "application/pdf",
            data=row.get("license_pdf_data"),
            uploaded_at=row.get("license_pdf_uploaded_at"),
        )

    hydrated_licenses = []
    for index, license_entry in enumerate(normalized_licenses):
        pdf_summary = license_documents.get(license_entry["id"])
        if pdf_summary is None and index == 0:
            pdf_summary = legacy_pdf
        hydrated_licenses.append({
            **license_entry,
            "pdf": pdf_summary,
        })

    payload = {
        "name": clean_profile_text(row.get("name")),
        "email": clean_profile_text(row.get("email")),
        "licenses": hydrated_licenses,
        "updated_at": row.get("updated_at"),
    }

    return payload


def get_user_profile_license_document_summaries(conn: psycopg.Connection, user_id: str) -> dict[str, dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT license_id, filename, content_type, pdf_data, uploaded_at
            FROM user_profile_license_documents
            WHERE user_id=%s
            """,
            (user_id,),
        )
        rows = cur.fetchall()

    return {
        row["license_id"]: profile_license_document_summary(
            license_id=row["license_id"],
            filename=row["filename"],
            content_type=row["content_type"],
            data=row["pdf_data"],
            uploaded_at=row.get("uploaded_at"),
        )
        for row in rows
    }


def get_user_profile(conn: psycopg.Connection, user_id: str) -> dict:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM user_profile WHERE user_id=%s", (user_id,))
        row = cur.fetchone()
    return decode_user_profile_row(row, get_user_profile_license_document_summaries(conn, user_id))


def save_user_profile(conn: psycopg.Connection, user_id: str, payload: dict | None) -> dict:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM user_profile WHERE user_id=%s", (user_id,))
        row = cur.fetchone()

        existing = row or {}
        updated_at = now_iso()
        licenses = normalize_profile_licenses((payload or {}).get("licenses"))
        primary_license = licenses[0] if licenses else {}
        cur.execute(
            """
            INSERT INTO user_profile(
                user_id, name, email, licenses_json, certification, registry,
                license_company, license_certification_name, license_student_number, license_certification_date, license_instructor_number,
                license_pdf_name, license_pdf_content_type, license_pdf_data, license_pdf_uploaded_at, updated_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id)
            DO UPDATE SET
                name=excluded.name,
                email=excluded.email,
                licenses_json=excluded.licenses_json,
                certification=excluded.certification,
                registry=excluded.registry,
                license_company=excluded.license_company,
                license_certification_name=excluded.license_certification_name,
                license_student_number=excluded.license_student_number,
                license_certification_date=excluded.license_certification_date,
                license_instructor_number=excluded.license_instructor_number,
                license_pdf_name=excluded.license_pdf_name,
                license_pdf_content_type=excluded.license_pdf_content_type,
                license_pdf_data=excluded.license_pdf_data,
                license_pdf_uploaded_at=excluded.license_pdf_uploaded_at,
                updated_at=excluded.updated_at
            """,
            (
                user_id,
                clean_profile_text((payload or {}).get("name")),
                clean_profile_text((payload or {}).get("email")),
                Jsonb(licenses),
                clean_profile_text(primary_license.get("certification_name")),
                clean_profile_text(primary_license.get("student_number")),
                clean_profile_text(primary_license.get("company")),
                clean_profile_text(primary_license.get("certification_name")),
                clean_profile_text(primary_license.get("student_number")),
                clean_profile_text(primary_license.get("certification_date")),
                clean_profile_text(primary_license.get("instructor_number")),
                existing.get("license_pdf_name"),
                existing.get("license_pdf_content_type"),
                existing.get("license_pdf_data"),
                existing.get("license_pdf_uploaded_at"),
                updated_at,
            ),
        )
        if licenses:
            cur.execute(
                "DELETE FROM user_profile_license_documents WHERE user_id=%s AND license_id <> ALL(%s)",
                (user_id, [license["id"] for license in licenses]),
            )
        else:
            cur.execute("DELETE FROM user_profile_license_documents WHERE user_id=%s", (user_id,))
    conn.commit()
    return get_user_profile(conn, user_id)


def save_user_profile_license_pdf(
    conn: psycopg.Connection,
    user_id: str,
    *,
    license_id: str,
    filename: str,
    content_type: str,
    pdf_bytes: bytes,
) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM user_profile WHERE user_id=%s", (user_id,))
        row = cur.fetchone()

        existing = row or {}
        existing_licenses = normalize_profile_licenses(existing.get("licenses_json"))
        if not any(license["id"] == license_id for license in existing_licenses):
            legacy_license = normalize_profile_license(
                {
                    "id": "license-1",
                    "company": existing.get("license_company"),
                    "certification_name": existing.get("license_certification_name") or existing.get("certification"),
                    "student_number": existing.get("license_student_number") or existing.get("registry"),
                    "certification_date": existing.get("license_certification_date"),
                    "instructor_number": existing.get("license_instructor_number"),
                }
            )
            if not (profile_license_has_values(legacy_license) and legacy_license["id"] == license_id):
                return None

        uploaded_at = now_iso()
        primary_license_id = existing_licenses[0]["id"] if existing_licenses else "license-1"
        legacy_filename = existing.get("license_pdf_name")
        legacy_content_type = existing.get("license_pdf_content_type")
        legacy_pdf_data = existing.get("license_pdf_data")
        legacy_uploaded_at = existing.get("license_pdf_uploaded_at")
        if license_id == primary_license_id:
            legacy_filename = filename
            legacy_content_type = content_type
            legacy_pdf_data = pdf_bytes
            legacy_uploaded_at = uploaded_at
        cur.execute(
            """
            INSERT INTO user_profile(
                user_id, name, email, licenses_json, certification, registry,
                license_company, license_certification_name, license_student_number, license_certification_date, license_instructor_number,
                license_pdf_name, license_pdf_content_type, license_pdf_data, license_pdf_uploaded_at, updated_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id)
            DO UPDATE SET
                name=excluded.name,
                email=excluded.email,
                licenses_json=excluded.licenses_json,
                certification=excluded.certification,
                registry=excluded.registry,
                license_company=excluded.license_company,
                license_certification_name=excluded.license_certification_name,
                license_student_number=excluded.license_student_number,
                license_certification_date=excluded.license_certification_date,
                license_instructor_number=excluded.license_instructor_number,
                license_pdf_name=excluded.license_pdf_name,
                license_pdf_content_type=excluded.license_pdf_content_type,
                license_pdf_data=excluded.license_pdf_data,
                license_pdf_uploaded_at=excluded.license_pdf_uploaded_at,
                updated_at=excluded.updated_at
            """,
            (
                user_id,
                clean_profile_text(existing.get("name")),
                clean_profile_text(existing.get("email")),
                Jsonb(normalize_profile_licenses(existing.get("licenses_json"))),
                clean_profile_text(existing.get("certification")),
                clean_profile_text(existing.get("registry")),
                clean_profile_text(existing.get("license_company")),
                clean_profile_text(existing.get("license_certification_name")),
                clean_profile_text(existing.get("license_student_number")),
                clean_profile_text(existing.get("license_certification_date")),
                clean_profile_text(existing.get("license_instructor_number")),
                legacy_filename,
                legacy_content_type,
                legacy_pdf_data,
                legacy_uploaded_at,
                uploaded_at,
            ),
        )
        cur.execute(
            """
            INSERT INTO user_profile_license_documents(user_id, license_id, filename, content_type, pdf_data, uploaded_at)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, license_id)
            DO UPDATE SET
                filename=excluded.filename,
                content_type=excluded.content_type,
                pdf_data=excluded.pdf_data,
                uploaded_at=excluded.uploaded_at
            """,
            (user_id, license_id, filename, content_type, pdf_bytes, uploaded_at),
        )
    conn.commit()
    return get_user_profile(conn, user_id)


def get_user_profile_license_pdf(conn: psycopg.Connection, user_id: str, license_id: str) -> dict | None:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT filename, content_type, pdf_data, uploaded_at
            FROM user_profile_license_documents
            WHERE user_id=%s AND license_id=%s
            """,
            (user_id, license_id),
        )
        row = cur.fetchone()
    if row and row.get("pdf_data") is not None:
        return {
            "filename": row.get("filename") or "diving-licenses.pdf",
            "content_type": row.get("content_type") or "application/pdf",
            "data": row.get("pdf_data"),
            "uploaded_at": row.get("uploaded_at"),
        }

    with conn.cursor() as cur:
        cur.execute("SELECT * FROM user_profile WHERE user_id=%s", (user_id,))
        profile_row = cur.fetchone()
    if not profile_row:
        return None

    licenses = normalize_profile_licenses(profile_row.get("licenses_json"))
    if not licenses:
        legacy_license = normalize_profile_license(
            {
                "id": "license-1",
                "company": profile_row.get("license_company"),
                "certification_name": profile_row.get("license_certification_name") or profile_row.get("certification"),
                "student_number": profile_row.get("license_student_number") or profile_row.get("registry"),
                "certification_date": profile_row.get("license_certification_date"),
                "instructor_number": profile_row.get("license_instructor_number"),
            }
        )
        if profile_license_has_values(legacy_license):
            licenses = [legacy_license]

    if licenses and licenses[0]["id"] == license_id and profile_row.get("license_pdf_data") is not None:
        return {
            "filename": profile_row.get("license_pdf_name") or "diving-licenses.pdf",
            "content_type": profile_row.get("license_pdf_content_type") or "application/pdf",
            "data": profile_row.get("license_pdf_data"),
            "uploaded_at": profile_row.get("license_pdf_uploaded_at"),
        }
    return None


def delete_dive(conn: psycopg.Connection, user_id: str, dive_id: int) -> bool:
    with conn.cursor() as cur:
        cur.execute("DELETE FROM dives WHERE user_id=%s AND id=%s RETURNING id", (user_id, dive_id))
        deleted = cur.fetchone() is not None
    conn.commit()
    return deleted


def sanitize_logbook_payload(payload: dict | None, existing_logbook: dict | None = None) -> dict:
    source = payload or {}
    if isinstance(source.get("logbook"), dict):
        source = source["logbook"]
    commit = bool((payload or {}).get("commit"))
    existing = normalize_logbook(existing_logbook)

    logbook = {
        "site": clean_logbook_text(source.get("site")),
        "buddy": clean_logbook_text(source.get("buddy")),
        "guide": clean_logbook_text(source.get("guide")),
        "notes": clean_logbook_text(source.get("notes")),
        "updated_at": now_iso(),
        "status": "imported",
    }

    if all(logbook[key] for key in LOGBOOK_REQUIRED_FIELDS) and (commit or existing.get("status") == "complete"):
        logbook["status"] = "complete"
        existing_completed_at = existing.get("completed_at") or source.get("completed_at")
        logbook["completed_at"] = existing_completed_at if isinstance(existing_completed_at, str) and existing_completed_at else now_iso()

    return logbook


def update_dive_logbook(conn: psycopg.Connection, user_id: str, dive_id: int, payload: dict | None) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM dives WHERE user_id=%s AND id=%s", (user_id, dive_id))
        row = cur.fetchone()
        if not row:
            return None

        fields = row.get("fields_json") or {}
        samples = row.get("samples_json") or []
        if not isinstance(fields, dict):
            fields = json.loads(fields)
        if isinstance(samples, str):
            samples = json.loads(samples)
        fields = normalize_dive_fields(fields, samples=samples, duration_seconds=resolve_duration_seconds(row))
        fields["logbook"] = sanitize_logbook_payload(payload, fields.get("logbook"))

        cur.execute(
            "UPDATE dives SET fields_json=%s WHERE user_id=%s AND id=%s",
            (Jsonb(fields), user_id, dive_id),
        )
    conn.commit()
    return get_dive(conn, user_id, dive_id, include_raw_data=False)


def import_sqlite_device_state(conn: psycopg.Connection, rows: list[dict], *, user_id: str = "legacy") -> int:
    if not rows:
        return 0
    with conn.cursor() as cur:
        for row in rows:
            cur.execute(
                """
                INSERT INTO device_state(user_id, vendor, product, fingerprint_hex, updated_at)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (user_id, vendor, product)
                DO UPDATE SET fingerprint_hex=excluded.fingerprint_hex, updated_at=excluded.updated_at
                """,
                (user_id, row["vendor"], row["product"], row["fingerprint_hex"], row["updated_at"]),
            )
    conn.commit()
    return len(rows)


def import_sqlite_dive_rows(conn: psycopg.Connection, rows: list[dict], *, user_id: str = "legacy") -> int:
    if not rows:
        return 0
    inserted = 0
    with conn.cursor() as cur:
        for row in rows:
            fields = row["fields_json"]
            samples = row["samples_json"]
            if isinstance(fields, str):
                fields = json.loads(fields)
            if isinstance(samples, str):
                samples = json.loads(samples)
            duration_ms = resolve_duration_milliseconds(row)
            fields = normalize_dive_fields(fields, samples=samples, duration_seconds=duration_milliseconds_to_seconds(duration_ms))
            import_payload = row.get("import_payload_json")
            if isinstance(import_payload, str):
                import_payload = json.loads(import_payload)
            if not isinstance(import_payload, dict) or not import_payload:
                import_payload = build_import_payload_from_row(row, fields, samples)

            cur.execute(
                """
                INSERT INTO dives(
                    id, user_id, vendor, product, fingerprint_hex, dive_uid, started_at,
                    duration_seconds, duration_ms, max_depth_m, avg_depth_m, import_payload_json,
                    fields_json, raw_sha256, raw_data, samples_json, imported_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (user_id, dive_uid) DO NOTHING
                RETURNING id
                """,
                (
                    row["id"],
                    user_id,
                    row["vendor"],
                    row["product"],
                    row["fingerprint_hex"],
                    row["dive_uid"],
                    row["started_at"],
                    None,
                    duration_ms,
                    row["max_depth_m"],
                    row["avg_depth_m"],
                    Jsonb(import_payload),
                    Jsonb(fields),
                    row["raw_sha256"],
                    row["raw_data"],
                    Jsonb(samples),
                    row["imported_at"],
                ),
            )
            if cur.fetchone() is not None:
                inserted += 1

        cur.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('dives', 'id'),
                COALESCE((SELECT MAX(id) FROM dives), 1),
                true
            )
            """
        )
    conn.commit()
    return inserted


def decode_base64_payload(payload: dict) -> bytes:
    try:
        return base64.b64decode(payload["raw_data_b64"], validate=True)
    except (ValueError, binascii.Error) as exc:
        raise ValueError("raw_data_b64 must be valid base64") from exc
