from __future__ import annotations

import base64
import binascii
import json
import re
import secrets
import time
from collections.abc import Callable
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb


SCHEMA = """
CREATE TABLE IF NOT EXISTS device_state (
    user_id TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, vendor, product)
);

CREATE TABLE IF NOT EXISTS dives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    dive_uid TEXT NOT NULL,
    started_at TEXT,
    duration_seconds INTEGER,
    duration_ms BIGINT,
    max_depth_m DOUBLE PRECISION,
    avg_depth_m DOUBLE PRECISION,
    import_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fields_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_sha256 TEXT NOT NULL,
    raw_data BYTEA NOT NULL,
    samples_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    imported_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_profile (
    user_id TEXT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    public_dives_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_slug TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_profile_license_documents (
    user_id TEXT NOT NULL,
    license_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    pdf_data BYTEA NOT NULL,
    uploaded_at TEXT NOT NULL,
    PRIMARY KEY (user_id, license_id)
);

CREATE TABLE IF NOT EXISTS user_profile_licenses (
    user_id TEXT NOT NULL,
    license_id TEXT NOT NULL,
    company TEXT,
    certification_name TEXT,
    student_number TEXT,
    certification_date TEXT,
    instructor_number TEXT,
    PRIMARY KEY (user_id, license_id)
);

CREATE TABLE IF NOT EXISTS user_profile_dive_sites (
    user_id TEXT NOT NULL,
    site_id TEXT NOT NULL,
    name TEXT,
    location TEXT,
    country TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    PRIMARY KEY (user_id, site_id)
);

CREATE TABLE IF NOT EXISTS user_profile_buddies (
    user_id TEXT NOT NULL,
    buddy_id TEXT NOT NULL,
    name TEXT,
    PRIMARY KEY (user_id, buddy_id)
);

CREATE TABLE IF NOT EXISTS user_profile_guides (
    user_id TEXT NOT NULL,
    guide_id TEXT NOT NULL,
    name TEXT,
    PRIMARY KEY (user_id, guide_id)
);

CREATE TABLE IF NOT EXISTS cli_sync_auth_requests (
    code TEXT PRIMARY KEY,
    status TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    approved_at BIGINT,
    token TEXT UNIQUE,
    token_expires_at BIGINT,
    user_id TEXT,
    email TEXT,
    session_id TEXT
);

CREATE TABLE IF NOT EXISTS auth_users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_login_at TEXT
);

CREATE TABLE IF NOT EXISTS auth_instance_settings (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    initialized BOOLEAN NOT NULL DEFAULT FALSE,
    public_registration_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    owner_user_id TEXT,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_user_invites (
    token TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'user',
    invited_by_user_id TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    accepted_at BIGINT
);
"""

LOGBOOK_REQUIRED_FIELDS = ("site", "buddy", "guide")
SAMPLE_TIME_UNIT_SECONDS = "seconds"
SAMPLE_TIME_UNIT_MILLISECONDS = "milliseconds"
CURRENT_SCHEMA_VERSION = 7
SCHEMA_VERSION_SQL = """
CREATE TABLE IF NOT EXISTS app_schema_version (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    version INTEGER NOT NULL,
    updated_at TEXT NOT NULL
);
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def ensure_schema_version_table(cur: psycopg.Cursor) -> None:
    cur.execute(SCHEMA_VERSION_SQL)
    cur.execute(
        """
        INSERT INTO app_schema_version(singleton, version, updated_at)
        VALUES (TRUE, 0, %s)
        ON CONFLICT (singleton) DO NOTHING
        """,
        (now_iso(),),
    )


def get_schema_version(cur: psycopg.Cursor) -> int:
    ensure_schema_version_table(cur)
    cur.execute("SELECT version FROM app_schema_version WHERE singleton=TRUE")
    row = cur.fetchone()
    if isinstance(row, dict):
        return int(row.get("version") or 0)
    if isinstance(row, tuple):
        return int(row[0] or 0)
    return 0


def set_schema_version(cur: psycopg.Cursor, version: int) -> None:
    cur.execute(
        """
        UPDATE app_schema_version
        SET version=%s, updated_at=%s
        WHERE singleton=TRUE
        """,
        (version, now_iso()),
    )


def get_db_schema_version(conn: psycopg.Connection) -> int:
    with conn.cursor() as cur:
        return get_schema_version(cur)


def apply_schema_migration_v1(cur: psycopg.Cursor) -> None:
    cur.execute("ALTER TABLE device_state ADD COLUMN IF NOT EXISTS user_id TEXT")
    cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS user_id TEXT")
    cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS duration_ms BIGINT")
    cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS import_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb")
    cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS fields_json JSONB NOT NULL DEFAULT '{}'::jsonb")
    cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS samples_json JSONB NOT NULL DEFAULT '[]'::jsonb")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS name TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS email TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS public_dives_enabled BOOLEAN NOT NULL DEFAULT FALSE")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS public_slug TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS licenses_json JSONB NOT NULL DEFAULT '[]'::jsonb")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS dive_sites_json JSONB NOT NULL DEFAULT '[]'::jsonb")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS buddies_json JSONB NOT NULL DEFAULT '[]'::jsonb")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS guides_json JSONB NOT NULL DEFAULT '[]'::jsonb")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS certification TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS registry TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_company TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_certification_name TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_student_number TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_certification_date TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_instructor_number TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_name TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_content_type TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_data BYTEA")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_uploaded_at TEXT")
    cur.execute("ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS updated_at TEXT")
    cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS user_id TEXT")
    cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS license_id TEXT")
    cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS filename TEXT")
    cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS content_type TEXT")
    cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS pdf_data BYTEA")
    cur.execute("ALTER TABLE user_profile_license_documents ADD COLUMN IF NOT EXISTS uploaded_at TEXT")
    cur.execute("UPDATE device_state SET user_id='legacy' WHERE user_id IS NULL")
    cur.execute("UPDATE dives SET user_id='legacy' WHERE user_id IS NULL")
    cur.execute("UPDATE user_profile SET public_dives_enabled=FALSE WHERE public_dives_enabled IS NULL")
    cur.execute("UPDATE user_profile SET updated_at=%s WHERE updated_at IS NULL", (now_iso(),))
    cur.execute(
        """
        UPDATE user_profile
        SET licenses_json = jsonb_build_array(
            jsonb_strip_nulls(
                jsonb_build_object(
                    'company', NULLIF(BTRIM(COALESCE(license_company, '')), ''),
                    'certification_name', NULLIF(BTRIM(COALESCE(license_certification_name, certification, '')), ''),
                    'student_number', NULLIF(BTRIM(COALESCE(license_student_number, registry, '')), ''),
                    'certification_date', NULLIF(BTRIM(COALESCE(license_certification_date, '')), ''),
                    'instructor_number', NULLIF(BTRIM(COALESCE(license_instructor_number, '')), '')
                )
            )
        )
        WHERE (licenses_json = '[]'::jsonb OR licenses_json IS NULL)
          AND (
                NULLIF(BTRIM(COALESCE(license_company, '')), '') IS NOT NULL
             OR NULLIF(BTRIM(COALESCE(license_certification_name, certification, '')), '') IS NOT NULL
             OR NULLIF(BTRIM(COALESCE(license_student_number, registry, '')), '') IS NOT NULL
             OR NULLIF(BTRIM(COALESCE(license_certification_date, '')), '') IS NOT NULL
             OR NULLIF(BTRIM(COALESCE(license_instructor_number, '')), '') IS NOT NULL
          )
        """
    )
    cur.execute(
        """
        UPDATE dives
        SET duration_ms = duration_seconds::bigint * 1000
        WHERE duration_ms IS NULL
          AND duration_seconds IS NOT NULL
        """
    )
    cur.execute(
        """
        UPDATE dives
        SET import_payload_json = jsonb_build_object(
            'vendor', vendor,
            'product', product,
            'fingerprint_hex', fingerprint_hex,
            'dive_uid', dive_uid,
            'started_at', started_at,
            'duration_ms', duration_ms,
            'duration_seconds', CASE
                WHEN duration_ms IS NOT NULL THEN (duration_ms / 1000)::bigint
                ELSE duration_seconds
            END,
            'max_depth_m', max_depth_m,
            'avg_depth_m', avg_depth_m,
            'fields', COALESCE(fields_json, '{}'::jsonb),
            'raw_sha256', raw_sha256,
            'samples', COALESCE(samples_json, '[]'::jsonb),
            'imported_at', imported_at
        )
        WHERE import_payload_json = '{}'::jsonb
        """
    )
    cur.execute("UPDATE dives SET duration_seconds = NULL WHERE duration_ms IS NOT NULL")
    cur.execute("ALTER TABLE device_state ALTER COLUMN user_id SET NOT NULL")
    cur.execute("ALTER TABLE dives ALTER COLUMN user_id SET NOT NULL")
    cur.execute("ALTER TABLE user_profile ALTER COLUMN public_dives_enabled SET NOT NULL")
    cur.execute("ALTER TABLE user_profile ALTER COLUMN updated_at SET NOT NULL")
    cur.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'device_state'::regclass
                  AND conname = 'device_state_pkey'
            ) THEN
                ALTER TABLE device_state DROP CONSTRAINT device_state_pkey;
            END IF;
        END $$;
        """
    )
    cur.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'device_state'::regclass
                  AND conname = 'device_state_pkey'
            ) THEN
                ALTER TABLE device_state
                ADD CONSTRAINT device_state_pkey PRIMARY KEY (user_id, vendor, product);
            END IF;
        END $$;
        """
    )
    cur.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'dives'::regclass
                  AND conname = 'dives_dive_uid_key'
            ) THEN
                ALTER TABLE dives DROP CONSTRAINT dives_dive_uid_key;
            END IF;
        END $$;
        """
    )
    cur.execute("DROP INDEX IF EXISTS idx_dives_started_at")
    cur.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_dives_user_dive_uid ON dives (user_id, dive_uid)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_dives_user_started_at ON dives (user_id, started_at DESC, id DESC)")
    cur.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profile_public_slug
        ON user_profile (public_slug)
        WHERE NULLIF(BTRIM(COALESCE(public_slug, '')), '') IS NOT NULL
        """
    )
    cur.execute("ALTER TABLE user_profile_guides DROP COLUMN IF EXISTS sort_order")
    cur.execute("DROP INDEX IF EXISTS idx_user_profile_guides_user_sort")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_user_profile_guides_user_name ON user_profile_guides (user_id, LOWER(name), name, guide_id)")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS status TEXT")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS created_at BIGINT")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS expires_at BIGINT")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS approved_at BIGINT")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS token TEXT")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS token_expires_at BIGINT")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS user_id TEXT")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS email TEXT")
    cur.execute("ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS session_id TEXT")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_cli_sync_auth_requests_expires_at ON cli_sync_auth_requests (expires_at)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_cli_sync_auth_requests_token_expires_at ON cli_sync_auth_requests (token_expires_at)")
    cur.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_cli_sync_auth_requests_token ON cli_sync_auth_requests (token) WHERE token IS NOT NULL")


def apply_schema_migration_v2(conn: psycopg.Connection, cur: psycopg.Cursor) -> None:
    with conn.cursor(row_factory=dict_row) as read_cur:
        read_cur.execute("SELECT id, fields_json FROM dives")
        rows = read_cur.fetchall()

    for row in rows:
        fields = row.get("fields_json") or {}
        if isinstance(fields, str):
            fields = json.loads(fields)
        if not isinstance(fields, dict):
            fields = {}

        tanks = list(fields.get("tanks") or []) if isinstance(fields.get("tanks"), list) else []
        primary_tank = dict(tanks[0]) if tanks and isinstance(tanks[0], dict) else {}
        if clean_tank_volume_value(primary_tank.get("volume")) is not None:
            continue

        primary_tank["volume"] = 12.0
        if tanks:
            tanks[0] = primary_tank
        else:
            tanks = [primary_tank]
        fields["tanks"] = tanks
        cur.execute("UPDATE dives SET fields_json=%s WHERE id=%s", (Jsonb(fields), row["id"]))


def migrate_legacy_profile_license_documents(conn: psycopg.Connection) -> None:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT user_id, license_company, license_certification_name, certification, license_student_number, registry,
                   license_certification_date, license_instructor_number, license_pdf_name, license_pdf_content_type,
                   license_pdf_data, license_pdf_uploaded_at
            FROM user_profile
            WHERE license_pdf_data IS NOT NULL
            """
        )
        rows = cur.fetchall()

    for row in rows:
        user_id = clean_profile_text(row.get("user_id"))
        if not user_id:
            continue

        licenses = fetch_user_profile_licenses(conn, user_id)
        if not licenses:
            licenses = legacy_profile_licenses_from_row(row)
        if not licenses:
            continue

        primary_license_id = licenses[0]["id"]
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO user_profile_license_documents(user_id, license_id, filename, content_type, pdf_data, uploaded_at)
                VALUES (%s, %s, %s, %s, %s, %s)
                ON CONFLICT (user_id, license_id)
                DO NOTHING
                """,
                (
                    user_id,
                    primary_license_id,
                    row.get("license_pdf_name") or "diving-licenses.pdf",
                    row.get("license_pdf_content_type") or "application/pdf",
                    row.get("license_pdf_data"),
                    row.get("license_pdf_uploaded_at"),
                ),
            )


def apply_schema_migration_v3(conn: psycopg.Connection, cur: psycopg.Cursor) -> None:
    backfill_profile_collection_tables(conn)
    migrate_legacy_profile_license_documents(conn)
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS licenses_json")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS dive_sites_json")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS buddies_json")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS guides_json")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS certification")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS registry")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_company")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_certification_name")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_student_number")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_certification_date")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_instructor_number")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_pdf_name")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_pdf_content_type")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_pdf_data")
    cur.execute("ALTER TABLE user_profile DROP COLUMN IF EXISTS license_pdf_uploaded_at")


def apply_schema_migration_v4(cur: psycopg.Cursor) -> None:
    cur.execute("UPDATE user_profile SET name='' WHERE name IS NULL")
    cur.execute("UPDATE user_profile SET email='' WHERE email IS NULL")
    cur.execute("UPDATE user_profile SET public_slug='' WHERE public_slug IS NULL")
    cur.execute("ALTER TABLE user_profile ALTER COLUMN name SET DEFAULT ''")
    cur.execute("ALTER TABLE user_profile ALTER COLUMN email SET DEFAULT ''")
    cur.execute("ALTER TABLE user_profile ALTER COLUMN public_slug SET DEFAULT ''")
    cur.execute("ALTER TABLE user_profile ALTER COLUMN name SET NOT NULL")
    cur.execute("ALTER TABLE user_profile ALTER COLUMN email SET NOT NULL")
    cur.execute("ALTER TABLE user_profile ALTER COLUMN public_slug SET NOT NULL")
    cur.execute("DROP INDEX IF EXISTS idx_user_profile_public_slug")
    cur.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profile_public_slug
        ON user_profile (public_slug)
        WHERE BTRIM(public_slug) <> ''
        """
    )


def apply_schema_migration_v5(cur: psycopg.Cursor) -> None:
    cur.execute("DROP INDEX IF EXISTS idx_user_profile_licenses_user_sort")
    cur.execute("DROP INDEX IF EXISTS idx_user_profile_dive_sites_user_sort")
    cur.execute("DROP INDEX IF EXISTS idx_user_profile_buddies_user_sort")
    cur.execute("ALTER TABLE user_profile_licenses DROP COLUMN IF EXISTS sort_order")
    cur.execute("ALTER TABLE user_profile_dive_sites DROP COLUMN IF EXISTS sort_order")
    cur.execute("ALTER TABLE user_profile_buddies DROP COLUMN IF EXISTS sort_order")


def apply_schema_migration_v6(cur: psycopg.Cursor) -> None:
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS auth_users (
            id TEXT PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            first_name TEXT NOT NULL DEFAULT '',
            last_name TEXT NOT NULL DEFAULT '',
            role TEXT NOT NULL DEFAULT 'user',
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_login_at TEXT
        )
        """
    )
    cur.execute("CREATE INDEX IF NOT EXISTS idx_auth_users_email ON auth_users (LOWER(email))")


def apply_schema_migration_v7(cur: psycopg.Cursor) -> None:
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS auth_instance_settings (
            singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
            initialized BOOLEAN NOT NULL DEFAULT FALSE,
            public_registration_enabled BOOLEAN NOT NULL DEFAULT FALSE,
            owner_user_id TEXT,
            updated_at TEXT NOT NULL
        )
        """
    )
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS auth_user_invites (
            token TEXT PRIMARY KEY,
            email TEXT NOT NULL,
            first_name TEXT NOT NULL DEFAULT '',
            last_name TEXT NOT NULL DEFAULT '',
            role TEXT NOT NULL DEFAULT 'user',
            invited_by_user_id TEXT NOT NULL,
            created_at BIGINT NOT NULL,
            expires_at BIGINT NOT NULL,
            accepted_at BIGINT
        )
        """
    )
    cur.execute("CREATE INDEX IF NOT EXISTS idx_auth_user_invites_expires_at ON auth_user_invites (expires_at)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_auth_user_invites_email ON auth_user_invites (LOWER(email))")
    cur.execute(
        """
        INSERT INTO auth_instance_settings(singleton, initialized, public_registration_enabled, owner_user_id, updated_at)
        VALUES (TRUE, FALSE, FALSE, NULL, %s)
        ON CONFLICT (singleton) DO NOTHING
        """,
        (now_iso(),),
    )
    cur.execute("SELECT id FROM auth_users ORDER BY created_at ASC, email ASC LIMIT 1")
    owner_row = cur.fetchone() or {}
    owner_user_id = owner_row.get("id") if isinstance(owner_row, dict) else None
    if owner_user_id:
        cur.execute(
            """
            UPDATE auth_instance_settings
            SET initialized=TRUE,
                owner_user_id=COALESCE(owner_user_id, %s),
                updated_at=%s
            WHERE singleton=TRUE
            """,
            (clean_profile_text(owner_user_id), now_iso()),
        )


def _run_schema_migrations(conn: psycopg.Connection, cur: psycopg.Cursor, current_version: int) -> int:
    migrations: tuple[tuple[int, Callable[[psycopg.Connection, psycopg.Cursor], None]], ...] = (
        (1, lambda _conn, migration_cur: apply_schema_migration_v1(migration_cur)),
        (2, apply_schema_migration_v2),
        (3, apply_schema_migration_v3),
        (4, lambda _conn, migration_cur: apply_schema_migration_v4(migration_cur)),
        (5, lambda _conn, migration_cur: apply_schema_migration_v5(migration_cur)),
        (6, lambda _conn, migration_cur: apply_schema_migration_v6(migration_cur)),
        (7, lambda _conn, migration_cur: apply_schema_migration_v7(migration_cur)),
    )
    target_schema_version = min(CURRENT_SCHEMA_VERSION, max(version for version, _ in migrations))

    for version, migration in migrations:
        if version > target_schema_version:
            break
        if current_version >= version:
            continue
        migration(conn, cur)
        set_schema_version(cur, version)
        current_version = version
    return current_version


def init_db(conn: psycopg.Connection) -> None:
    with conn.cursor() as cur:
        cur.execute(SCHEMA)
        ensure_schema_version_table(cur)
        current_version = get_schema_version(cur)
        _run_schema_migrations(conn, cur, current_version)

    conn.commit()


def open_db(database_url: str, *, ensure_schema: bool = False) -> psycopg.Connection:
    conn = psycopg.connect(database_url, row_factory=dict_row)
    if ensure_schema:
        init_db(conn)
    return conn


def cleanup_cli_sync_auth_with_cursor(cur: psycopg.Cursor, now_timestamp: int) -> None:
    cur.execute(
        """
        DELETE FROM cli_sync_auth_requests
        WHERE (status = 'pending' AND expires_at <= %s)
           OR (status = 'approved' AND COALESCE(token_expires_at, 0) <= %s)
        """,
        (now_timestamp, now_timestamp),
    )


def create_cli_sync_request(
    conn: psycopg.Connection,
    *,
    code: str,
    request_ttl_seconds: int,
    now_timestamp: int,
) -> dict:
    payload = {
        "code": code,
        "status": "pending",
        "created_at": now_timestamp,
        "expires_at": now_timestamp + max(request_ttl_seconds, 1),
        "token": None,
        "token_expires_at": None,
        "user_id": None,
        "email": None,
    }
    with conn.cursor() as cur:
        cleanup_cli_sync_auth_with_cursor(cur, now_timestamp)
        cur.execute(
            """
            INSERT INTO cli_sync_auth_requests(
                code, status, created_at, expires_at, approved_at, token, token_expires_at, user_id, email, session_id
            )
            VALUES (%s, %s, %s, %s, NULL, NULL, NULL, NULL, NULL, NULL)
            """,
            (
                payload["code"],
                payload["status"],
                payload["created_at"],
                payload["expires_at"],
            ),
        )
    conn.commit()
    return dict(payload)


def get_cli_sync_request_status(conn: psycopg.Connection, code: str, *, now_timestamp: int) -> dict | None:
    with conn.cursor() as cur:
        cleanup_cli_sync_auth_with_cursor(cur, now_timestamp)
        cur.execute(
            """
            SELECT code, status, created_at, expires_at, approved_at, token, token_expires_at, user_id, email
            FROM cli_sync_auth_requests
            WHERE code=%s
            """,
            (code,),
        )
        row = cur.fetchone()
    conn.commit()
    if not row:
        return None
    return {
        "code": row.get("code"),
        "status": row.get("status"),
        "created_at": row.get("created_at"),
        "expires_at": row.get("expires_at"),
        "approved_at": row.get("approved_at"),
        "token": row.get("token"),
        "token_expires_at": row.get("token_expires_at"),
        "user_id": row.get("user_id"),
        "email": row.get("email"),
    }


def approve_cli_sync_request(
    conn: psycopg.Connection,
    code: str,
    claims: dict,
    *,
    token: str,
    token_ttl_seconds: int,
    now_timestamp: int,
) -> dict | None:
    token_expires_at = now_timestamp + max(token_ttl_seconds, 1)
    with conn.cursor() as cur:
        cleanup_cli_sync_auth_with_cursor(cur, now_timestamp)
        cur.execute(
            """
            UPDATE cli_sync_auth_requests
            SET
                status='approved',
                approved_at=%s,
                token=%s,
                token_expires_at=%s,
                user_id=%s,
                email=%s,
                session_id=%s
            WHERE code=%s
              AND status='pending'
              AND expires_at > %s
            RETURNING code, status, created_at, expires_at, approved_at, token, token_expires_at, user_id, email
            """,
            (
                now_timestamp,
                token,
                token_expires_at,
                clean_profile_text(claims.get("sub")),
                clean_profile_text(claims.get("email")),
                clean_profile_text(claims.get("sid")),
                code,
                now_timestamp,
            ),
        )
        row = cur.fetchone()
    conn.commit()
    if not row:
        return None
    return {
        "code": row.get("code"),
        "status": row.get("status"),
        "created_at": row.get("created_at"),
        "expires_at": row.get("expires_at"),
        "approved_at": row.get("approved_at"),
        "token": row.get("token"),
        "token_expires_at": row.get("token_expires_at"),
        "user_id": row.get("user_id"),
        "email": row.get("email"),
    }


def verify_cli_sync_token(conn: psycopg.Connection, token: str, *, now_timestamp: int) -> dict | None:
    with conn.cursor() as cur:
        cleanup_cli_sync_auth_with_cursor(cur, now_timestamp)
        cur.execute(
            """
            SELECT user_id, email, session_id, approved_at, token_expires_at
            FROM cli_sync_auth_requests
            WHERE token=%s
              AND status='approved'
              AND token_expires_at > %s
            """,
            (token, now_timestamp),
        )
        row = cur.fetchone()
    conn.commit()
    if not row:
        return None
    return {
        "token_type": "cli_sync",
        "sub": row.get("user_id"),
        "email": row.get("email"),
        "sid": row.get("session_id"),
        "issued_at": row.get("approved_at"),
        "expires_at": row.get("token_expires_at"),
    }


def clean_logbook_text(value: object) -> str:
    return value.strip() if isinstance(value, str) else ""


def clean_profile_text(value: object) -> str:
    return value.strip() if isinstance(value, str) else ""


def clean_profile_bool(value: object) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return bool(value)
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"1", "true", "yes", "on"}:
            return True
        if normalized in {"0", "false", "no", "off", ""}:
            return False
    return False


def normalize_public_slug(value: object) -> str:
    source = clean_profile_text(value).lower()
    if not source:
        return ""
    normalized = re.sub(r"[^a-z0-9]+", "-", source)
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-")
    return normalized[:48]


def generate_public_slug() -> str:
    return f"diver-{secrets.token_hex(4)}"


def ensure_unique_public_slug(cur: psycopg.Cursor, user_id: str, desired_slug: object, existing_slug: object = None) -> str:
    existing = normalize_public_slug(existing_slug)
    requested = normalize_public_slug(desired_slug)
    if existing and requested == existing:
        return existing

    base = requested or existing or generate_public_slug()
    suffix = 1

    while True:
        candidate = base if suffix == 1 else f"{base[: max(1, 48 - len(str(suffix)) - 1)]}-{suffix}"
        cur.execute("SELECT user_id FROM user_profile WHERE public_slug=%s", (candidate,))
        row = cur.fetchone()
        if not row or clean_profile_text(row.get("user_id")) == user_id:
            return candidate
        if requested or existing:
            suffix += 1
            continue
        base = generate_public_slug()
        suffix = 1


def clean_coordinate_value(value: object) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        parsed = float(value)
        return parsed if parsed == parsed and parsed not in {float("inf"), float("-inf")} else None
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return None
        try:
            parsed = float(stripped)
        except ValueError:
            return None
        return parsed if parsed == parsed and parsed not in {float("inf"), float("-inf")} else None
    return None


def clean_tank_volume_value(value: object) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        parsed = float(value)
    elif isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return None
        try:
            parsed = float(stripped)
        except ValueError:
            return None
    else:
        return None
    if parsed != parsed or parsed in {float("inf"), float("-inf")}:
        return None
    if parsed not in {9.0, 12.0, 15.0}:
        return None
    return parsed


def normalize_profile_license(entry: dict | None) -> dict:
    source = entry if isinstance(entry, dict) else {}
    return {
        "id": clean_profile_text(source.get("id")),
        "company": clean_profile_text(source.get("company")),
        "certification_name": clean_profile_text(source.get("certification_name")),
        "student_number": clean_profile_text(source.get("student_number")),
        "certification_date": clean_profile_text(source.get("certification_date")),
        "instructor_number": clean_profile_text(source.get("instructor_number")),
    }


def profile_license_has_values(entry: dict | None) -> bool:
    license_entry = normalize_profile_license(entry)
    return any(value for key, value in license_entry.items() if key != "id")


def normalize_profile_licenses(entries: object) -> list[dict]:
    if not isinstance(entries, list):
        return []
    normalized: list[dict] = []
    seen_ids: set[str] = set()
    next_fallback = 1

    for entry in entries:
        if not isinstance(entry, dict):
            continue
        normalized_entry = normalize_profile_license(entry)
        if not profile_license_has_values(normalized_entry):
            continue

        license_id = normalized_entry["id"] or f"license-{next_fallback}"
        next_fallback += 1
        dedupe_suffix = 1
        base_id = license_id
        while license_id in seen_ids:
            dedupe_suffix += 1
            license_id = f"{base_id}-{dedupe_suffix}"

        normalized_entry["id"] = license_id
        seen_ids.add(license_id)
        normalized.append(normalized_entry)

    return normalized


def normalize_profile_dive_site(entry: dict | None) -> dict:
    source = entry if isinstance(entry, dict) else {}
    latitude = clean_coordinate_value(source.get("latitude") if "latitude" in source else source.get("lat"))
    longitude = clean_coordinate_value(source.get("longitude") if "longitude" in source else source.get("lon"))
    if latitude is not None and not (-90 <= latitude <= 90):
        latitude = None
    if longitude is not None and not (-180 <= longitude <= 180):
        longitude = None
    return {
        "id": clean_profile_text(source.get("id")),
        "name": clean_profile_text(source.get("name")),
        "location": clean_profile_text(source.get("location")),
        "country": clean_profile_text(source.get("country")),
        "latitude": latitude,
        "longitude": longitude,
    }


def profile_dive_site_has_values(entry: dict | None) -> bool:
    return bool(normalize_profile_dive_site(entry).get("name"))


def normalize_profile_dive_sites(entries: object) -> list[dict]:
    if not isinstance(entries, list):
        return []

    normalized: list[dict] = []
    seen_ids: set[str] = set()
    next_fallback = 1

    for entry in entries:
        if not isinstance(entry, dict):
            continue
        normalized_entry = normalize_profile_dive_site(entry)
        if not profile_dive_site_has_values(normalized_entry):
            continue

        site_id = normalized_entry["id"] or f"site-{next_fallback}"
        next_fallback += 1
        dedupe_suffix = 1
        base_id = site_id
        while site_id in seen_ids:
            dedupe_suffix += 1
            site_id = f"{base_id}-{dedupe_suffix}"

        normalized_entry["id"] = site_id
        seen_ids.add(site_id)
        normalized.append(normalized_entry)

    return normalized


def normalize_profile_buddy(entry: dict | None) -> dict:
    source = entry if isinstance(entry, dict) else {}
    return {
        "id": clean_profile_text(source.get("id")),
        "name": clean_profile_text(source.get("name")),
    }


def profile_buddy_has_values(entry: dict | None) -> bool:
    return bool(normalize_profile_buddy(entry).get("name"))


def normalize_profile_buddies(entries: object) -> list[dict]:
    if not isinstance(entries, list):
        return []

    normalized: list[dict] = []
    seen_ids: set[str] = set()
    next_fallback = 1

    for entry in entries:
        if not isinstance(entry, dict):
            continue
        normalized_entry = normalize_profile_buddy(entry)
        if not profile_buddy_has_values(normalized_entry):
            continue

        buddy_id = normalized_entry["id"] or f"buddy-{next_fallback}"
        next_fallback += 1
        dedupe_suffix = 1
        base_id = buddy_id
        while buddy_id in seen_ids:
            dedupe_suffix += 1
            buddy_id = f"{base_id}-{dedupe_suffix}"

        normalized_entry["id"] = buddy_id
        seen_ids.add(buddy_id)
        normalized.append(normalized_entry)

    return normalized


def normalize_profile_guide(entry: dict | None) -> dict:
    source = entry if isinstance(entry, dict) else {}
    return {
        "id": clean_profile_text(source.get("id")),
        "name": clean_profile_text(source.get("name")),
    }


def profile_guide_has_values(entry: dict | None) -> bool:
    return bool(normalize_profile_guide(entry).get("name"))


def normalize_profile_guides(entries: object) -> list[dict]:
    if not isinstance(entries, list):
        return []

    normalized: list[dict] = []
    seen_ids: set[str] = set()
    next_fallback = 1

    for entry in entries:
        if not isinstance(entry, dict):
            continue
        normalized_entry = normalize_profile_guide(entry)
        if not profile_guide_has_values(normalized_entry):
            continue

        guide_id = normalized_entry["id"] or f"guide-{next_fallback}"
        next_fallback += 1
        dedupe_suffix = 1
        base_id = guide_id
        while guide_id in seen_ids:
            dedupe_suffix += 1
            guide_id = f"{base_id}-{dedupe_suffix}"

        normalized_entry["id"] = guide_id
        seen_ids.add(guide_id)
        normalized.append(normalized_entry)

    return normalized


def decode_profile_collection(value: object) -> list[dict]:
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except json.JSONDecodeError:
            return []
    return value if isinstance(value, list) else []


def legacy_profile_licenses_from_row(row: dict | None) -> list[dict]:
    source = row or {}
    normalized_licenses = normalize_profile_licenses(decode_profile_collection(source.get("licenses_json")))
    if normalized_licenses:
        return normalized_licenses

    legacy_license = normalize_profile_license(
        {
            "id": "license-1",
            "company": source.get("license_company"),
            "certification_name": source.get("license_certification_name") or source.get("certification"),
            "student_number": source.get("license_student_number") or source.get("registry"),
            "certification_date": source.get("license_certification_date"),
            "instructor_number": source.get("license_instructor_number"),
        }
    )
    return [legacy_license] if profile_license_has_values(legacy_license) else []


def legacy_profile_dive_sites_from_row(row: dict | None) -> list[dict]:
    return normalize_profile_dive_sites(decode_profile_collection((row or {}).get("dive_sites_json")))


def legacy_profile_buddies_from_row(row: dict | None) -> list[dict]:
    return normalize_profile_buddies(decode_profile_collection((row or {}).get("buddies_json")))


def legacy_profile_guides_from_row(row: dict | None) -> list[dict]:
    return normalize_profile_guides(decode_profile_collection((row or {}).get("guides_json")))


def fetch_user_profile_licenses(conn: psycopg.Connection, user_id: str) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT license_id, company, certification_name, student_number, certification_date, instructor_number
            FROM user_profile_licenses
            WHERE user_id=%s
            ORDER BY LOWER(COALESCE(certification_name, '')) ASC, LOWER(COALESCE(company, '')) ASC, license_id ASC
            """,
            (user_id,),
        )
        rows = cur.fetchall()

    return normalize_profile_licenses(
        [
            {
                "id": row.get("license_id"),
                "company": row.get("company"),
                "certification_name": row.get("certification_name"),
                "student_number": row.get("student_number"),
                "certification_date": row.get("certification_date"),
                "instructor_number": row.get("instructor_number"),
            }
            for row in rows
        ]
    )


def fetch_user_profile_dive_sites(conn: psycopg.Connection, user_id: str) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT site_id, name, location, country, latitude, longitude
            FROM user_profile_dive_sites
            WHERE user_id=%s
            ORDER BY LOWER(COALESCE(name, '')) ASC, LOWER(COALESCE(location, '')) ASC, site_id ASC
            """,
            (user_id,),
        )
        rows = cur.fetchall()

    return normalize_profile_dive_sites(
        [
            {
                "id": row.get("site_id"),
                "name": row.get("name"),
                "location": row.get("location"),
                "country": row.get("country"),
                "latitude": row.get("latitude"),
                "longitude": row.get("longitude"),
            }
            for row in rows
        ]
    )


def fetch_user_profile_buddies(conn: psycopg.Connection, user_id: str) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT buddy_id, name
            FROM user_profile_buddies
            WHERE user_id=%s
            ORDER BY LOWER(COALESCE(name, '')) ASC, buddy_id ASC
            """,
            (user_id,),
        )
        rows = cur.fetchall()

    return normalize_profile_buddies(
        [
            {
                "id": row.get("buddy_id"),
                "name": row.get("name"),
            }
            for row in rows
        ]
    )


def fetch_user_profile_guides(conn: psycopg.Connection, user_id: str) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT guide_id, name
            FROM user_profile_guides
            WHERE user_id=%s
            ORDER BY LOWER(name) ASC, name ASC, guide_id ASC
            """,
            (user_id,),
        )
        rows = cur.fetchall()

    return normalize_profile_guides(
        [
            {
                "id": row.get("guide_id"),
                "name": row.get("name"),
            }
            for row in rows
        ]
    )


def resolve_user_profile_collections(conn: psycopg.Connection, user_id: str, _row: dict | None) -> tuple[list[dict], list[dict], list[dict], list[dict]]:
    licenses = fetch_user_profile_licenses(conn, user_id)
    dive_sites = fetch_user_profile_dive_sites(conn, user_id)
    buddies = fetch_user_profile_buddies(conn, user_id)
    guides = fetch_user_profile_guides(conn, user_id)

    return licenses, dive_sites, buddies, guides


def replace_user_profile_licenses(cur: psycopg.Cursor, user_id: str, licenses: list[dict]) -> None:
    cur.execute("DELETE FROM user_profile_licenses WHERE user_id=%s", (user_id,))
    for license_entry in licenses:
        cur.execute(
            """
            INSERT INTO user_profile_licenses(
                user_id, license_id, company, certification_name, student_number, certification_date, instructor_number
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
            (
                user_id,
                license_entry["id"],
                clean_profile_text(license_entry.get("company")),
                clean_profile_text(license_entry.get("certification_name")),
                clean_profile_text(license_entry.get("student_number")),
                clean_profile_text(license_entry.get("certification_date")),
                clean_profile_text(license_entry.get("instructor_number")),
            ),
        )


def replace_user_profile_dive_sites(cur: psycopg.Cursor, user_id: str, dive_sites: list[dict]) -> None:
    cur.execute("DELETE FROM user_profile_dive_sites WHERE user_id=%s", (user_id,))
    for site in dive_sites:
        cur.execute(
            """
            INSERT INTO user_profile_dive_sites(
                user_id, site_id, name, location, country, latitude, longitude
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
            (
                user_id,
                site["id"],
                clean_profile_text(site.get("name")),
                clean_profile_text(site.get("location")),
                clean_profile_text(site.get("country")),
                clean_coordinate_value(site.get("latitude")),
                clean_coordinate_value(site.get("longitude")),
            ),
        )


def replace_user_profile_buddies(cur: psycopg.Cursor, user_id: str, buddies: list[dict]) -> None:
    cur.execute("DELETE FROM user_profile_buddies WHERE user_id=%s", (user_id,))
    for buddy in buddies:
        cur.execute(
            """
            INSERT INTO user_profile_buddies(user_id, buddy_id, name)
            VALUES (%s, %s, %s)
            """,
            (
                user_id,
                buddy["id"],
                clean_profile_text(buddy.get("name")),
            ),
        )


def replace_user_profile_guides(cur: psycopg.Cursor, user_id: str, guides: list[dict]) -> None:
    cur.execute("DELETE FROM user_profile_guides WHERE user_id=%s", (user_id,))
    for guide in guides:
        cur.execute(
            """
            INSERT INTO user_profile_guides(user_id, guide_id, name)
            VALUES (%s, %s, %s)
            """,
            (
                user_id,
                guide["id"],
                clean_profile_text(guide.get("name")),
            ),
        )


def backfill_profile_collection_tables(conn: psycopg.Connection) -> None:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute("SELECT * FROM user_profile")
        rows = cur.fetchall()

    for row in rows:
        user_id = clean_profile_text(row.get("user_id"))
        if not user_id:
            continue

        licenses = legacy_profile_licenses_from_row(row)
        dive_sites = legacy_profile_dive_sites_from_row(row)
        buddies = legacy_profile_buddies_from_row(row)
        guides = legacy_profile_guides_from_row(row)

        with conn.cursor() as cur:
            cur.execute("SELECT 1 FROM user_profile_licenses WHERE user_id=%s LIMIT 1", (user_id,))
            has_license_rows = cur.fetchone() is not None
            cur.execute("SELECT 1 FROM user_profile_dive_sites WHERE user_id=%s LIMIT 1", (user_id,))
            has_dive_site_rows = cur.fetchone() is not None
            cur.execute("SELECT 1 FROM user_profile_buddies WHERE user_id=%s LIMIT 1", (user_id,))
            has_buddy_rows = cur.fetchone() is not None
            cur.execute("SELECT 1 FROM user_profile_guides WHERE user_id=%s LIMIT 1", (user_id,))
            has_guide_rows = cur.fetchone() is not None

            if licenses and not has_license_rows:
                replace_user_profile_licenses(cur, user_id, licenses)
            if dive_sites and not has_dive_site_rows:
                replace_user_profile_dive_sites(cur, user_id, dive_sites)
            if buddies and not has_buddy_rows:
                replace_user_profile_buddies(cur, user_id, buddies)
            if guides and not has_guide_rows:
                replace_user_profile_guides(cur, user_id, guides)


def profile_license_document_summary(*, license_id: str, filename: str, content_type: str, data: bytes, uploaded_at: str | None) -> dict:
    return {
        "license_id": license_id,
        "filename": filename,
        "content_type": content_type,
        "size_bytes": len(data),
        "uploaded_at": uploaded_at,
        "preview_url": f"/api/profile/licenses/{license_id}/pdf",
    }


def numeric_int(value: object) -> int | None:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    return int(round(float(value)))


def duration_seconds_to_milliseconds(value: object) -> int | None:
    seconds = numeric_int(value)
    if seconds is None:
        return None
    return seconds * 1000


def duration_milliseconds_to_seconds(value: object) -> int | None:
    milliseconds = numeric_int(value)
    if milliseconds is None:
        return None
    return int(round(milliseconds / 1000))


def normalize_logbook(logbook: dict | None) -> dict:
    source = logbook if isinstance(logbook, dict) else {}
    status = "complete" if source.get("status") == "complete" else "imported"
    normalized = {
        "site": clean_logbook_text(source.get("site")),
        "buddy": clean_logbook_text(source.get("buddy")),
        "guide": clean_logbook_text(source.get("guide")),
        "notes": clean_logbook_text(source.get("notes")),
        "status": status,
    }

    updated_at = source.get("updated_at")
    if isinstance(updated_at, str) and updated_at:
        normalized["updated_at"] = updated_at

    completed_at = source.get("completed_at")
    if status == "complete" and isinstance(completed_at, str) and completed_at:
        normalized["completed_at"] = completed_at

    return normalized


def normalize_sample_time_unit(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    normalized = value.strip().lower()
    if normalized in {"s", "sec", "secs", "second", "seconds"}:
        return SAMPLE_TIME_UNIT_SECONDS
    if normalized in {"ms", "msec", "msecs", "millisecond", "milliseconds"}:
        return SAMPLE_TIME_UNIT_MILLISECONDS
    return None


def resolve_duration_milliseconds(source: dict | None) -> int | None:
    if not isinstance(source, dict):
        return None
    duration_ms = numeric_int(source.get("duration_ms"))
    if duration_ms is not None:
        return duration_ms
    return duration_seconds_to_milliseconds(source.get("duration_seconds"))


def resolve_duration_seconds(source: dict | None) -> int | None:
    duration_ms = resolve_duration_milliseconds(source)
    if duration_ms is not None:
        return duration_milliseconds_to_seconds(duration_ms)
    if not isinstance(source, dict):
        return None
    return numeric_int(source.get("duration_seconds"))


def infer_sample_time_unit(samples: list | None, duration_seconds: object) -> str | None:
    if not isinstance(samples, list):
        return None

    times = [
        sample.get("time_seconds")
        for sample in samples
        if isinstance(sample, dict) and isinstance(sample.get("time_seconds"), (int, float))
    ]
    if not times:
        return None

    duration = float(duration_seconds) if isinstance(duration_seconds, (int, float)) else 0.0
    max_time = max(times)
    if duration > 0 and max_time > duration * 5:
        return SAMPLE_TIME_UNIT_MILLISECONDS
    return SAMPLE_TIME_UNIT_SECONDS


def normalize_dive_fields(fields: dict | None, *, samples: list | None = None, duration_seconds: object = None) -> dict:
    normalized = dict(fields) if isinstance(fields, dict) else {}
    normalized["logbook"] = normalize_logbook(normalized.get("logbook"))
    sample_time_unit = normalize_sample_time_unit(normalized.get("sample_time_unit"))
    if sample_time_unit:
        normalized["sample_time_unit"] = sample_time_unit
    else:
        inferred_sample_time_unit = infer_sample_time_unit(samples, duration_seconds)
        if inferred_sample_time_unit:
            normalized["sample_time_unit"] = inferred_sample_time_unit
    return normalized


def is_logbook_complete(logbook: dict | None) -> bool:
    return normalize_logbook(logbook).get("status") == "complete"


def build_import_payload(payload: dict | None, *, imported_at: str) -> dict:
    archived = dict(payload) if isinstance(payload, dict) else {}
    archived.setdefault("imported_at", imported_at)
    duration_ms = resolve_duration_milliseconds(archived)
    if duration_ms is not None:
        archived["duration_ms"] = duration_ms
        archived.setdefault("duration_seconds", duration_milliseconds_to_seconds(duration_ms))
    archived.pop("raw_data_b64", None)
    return archived


def build_import_payload_from_row(row: dict, fields: dict, samples: list) -> dict:
    duration_ms = resolve_duration_milliseconds(row)
    return {
        "vendor": row["vendor"],
        "product": row["product"],
        "fingerprint_hex": row.get("fingerprint_hex"),
        "dive_uid": row["dive_uid"],
        "started_at": row.get("started_at"),
        "duration_ms": duration_ms,
        "duration_seconds": duration_milliseconds_to_seconds(duration_ms),
        "max_depth_m": row.get("max_depth_m"),
        "avg_depth_m": row.get("avg_depth_m"),
        "fields": fields,
        "raw_sha256": row["raw_sha256"],
        "samples": samples,
        "imported_at": row["imported_at"],
    }


def decode_dive_row(row: dict, include_samples: bool, include_raw_data: bool) -> dict:
    fields = row.get("fields_json") or {}
    samples = row.get("samples_json") or []
    raw_data = row.get("raw_data")
    duration_ms = resolve_duration_milliseconds(row)
    duration_seconds = duration_milliseconds_to_seconds(duration_ms)

    if isinstance(samples, str):
        samples = json.loads(samples)
    if not isinstance(fields, dict):
        fields = json.loads(fields)
    fields = normalize_dive_fields(fields, samples=samples, duration_seconds=duration_seconds)

    payload = {
        "id": row["id"],
        "vendor": row["vendor"],
        "product": row["product"],
        "fingerprint_hex": row.get("fingerprint_hex"),
        "dive_uid": row["dive_uid"],
        "started_at": row.get("started_at"),
        "duration_ms": duration_ms,
        "duration_seconds": duration_seconds,
        "max_depth_m": row.get("max_depth_m"),
        "avg_depth_m": row.get("avg_depth_m"),
        "fields": fields,
        "raw_sha256": row["raw_sha256"],
        "raw_data_size": len(raw_data) if raw_data is not None else 0,
        "imported_at": row["imported_at"],
    }

    payload["sample_count"] = len(samples)
    if include_samples:
        payload["samples"] = samples
    if include_raw_data and raw_data is not None:
        payload["raw_data_b64"] = base64.b64encode(raw_data).decode("ascii")
    return payload


def insert_dive_record(conn: psycopg.Connection, user_id: str, payload: dict) -> bool:
    imported_at = payload.get("imported_at") or now_iso()
    samples = payload.get("samples") or []
    duration_ms = resolve_duration_milliseconds(payload)
    duration_seconds = duration_milliseconds_to_seconds(duration_ms)
    fields = normalize_dive_fields(payload.get("fields"), samples=samples, duration_seconds=duration_seconds)
    raw_data = decode_base64_payload(payload)
    import_payload = build_import_payload(payload, imported_at=imported_at)

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO dives(
                user_id, vendor, product, fingerprint_hex, dive_uid, started_at,
                duration_seconds, duration_ms, max_depth_m, avg_depth_m, import_payload_json,
                fields_json, raw_sha256, raw_data, samples_json, imported_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, dive_uid) DO NOTHING
            RETURNING id
            """,
            (
                user_id,
                payload["vendor"],
                payload["product"],
                payload.get("fingerprint_hex"),
                payload["dive_uid"],
                payload.get("started_at"),
                None,
                duration_ms,
                payload.get("max_depth_m"),
                payload.get("avg_depth_m"),
                Jsonb(import_payload),
                Jsonb(fields),
                payload["raw_sha256"],
                raw_data,
                Jsonb(samples),
                imported_at,
            ),
        )
        inserted = cur.fetchone() is not None
    conn.commit()
    return inserted


def get_dive_id_by_uid(conn: psycopg.Connection, user_id: str, dive_uid: str) -> int | None:
    with conn.cursor() as cur:
        cur.execute("SELECT id FROM dives WHERE user_id=%s AND dive_uid=%s", (user_id, dive_uid))
        row = cur.fetchone()
    return row["id"] if row else None


def save_device_state(conn: psycopg.Connection, user_id: str, vendor: str, product: str, fingerprint_hex: str | None) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO device_state(user_id, vendor, product, fingerprint_hex, updated_at)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (user_id, vendor, product)
            DO UPDATE SET fingerprint_hex=excluded.fingerprint_hex, updated_at=excluded.updated_at
            """,
            (user_id, vendor, product, fingerprint_hex, now_iso()),
        )
    conn.commit()


def get_device_state(conn: psycopg.Connection, user_id: str, vendor: str, product: str) -> dict:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT vendor, product, fingerprint_hex, updated_at
            FROM device_state
            WHERE user_id=%s AND vendor=%s AND product=%s
            """,
            (user_id, vendor, product),
        )
        row = cur.fetchone()
    if not row:
        return {
            "vendor": vendor,
            "product": product,
            "fingerprint_hex": None,
            "updated_at": None,
        }
    return row


def list_device_states(conn: psycopg.Connection, user_id: str) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT vendor, product, fingerprint_hex, updated_at
            FROM device_state
            WHERE user_id=%s
            ORDER BY vendor ASC, product ASC
            """,
            (user_id,),
        )
        rows = cur.fetchall()
    return rows or []


def list_dives(
    conn: psycopg.Connection,
    user_id: str,
    include_samples: bool,
    include_raw_data: bool,
    limit: int,
    offset: int,
) -> tuple[list[dict], int]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT *
            FROM dives
            WHERE user_id=%s
            ORDER BY started_at DESC, id DESC
            LIMIT %s OFFSET %s
            """,
            (user_id, limit, offset),
        )
        rows = cur.fetchall()
        cur.execute("SELECT COUNT(*) AS total FROM dives WHERE user_id=%s", (user_id,))
        total = cur.fetchone()["total"]
    dives = [decode_dive_row(row, include_samples, include_raw_data) for row in rows]
    return dives, total


def list_all_dives(conn: psycopg.Connection, user_id: str, *, include_samples: bool, include_raw_data: bool) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT *
            FROM dives
            WHERE user_id=%s
            ORDER BY started_at DESC, id DESC
            """,
            (user_id,),
        )
        rows = cur.fetchall()
    return [decode_dive_row(row, include_samples, include_raw_data) for row in rows]


def public_dive_has_coordinates(dive: dict) -> bool:
    candidates = [
        dive.get("location"),
        dive.get("gps"),
        (dive.get("fields") or {}).get("location"),
        (dive.get("fields") or {}).get("gps"),
        (dive.get("fields") or {}).get("position"),
        (dive.get("fields") or {}).get("coordinates"),
    ]
    for candidate in candidates:
        if not isinstance(candidate, dict):
            continue
        latitude = clean_coordinate_value(candidate.get("lat") if "lat" in candidate else candidate.get("latitude"))
        longitude = clean_coordinate_value(
            candidate.get("lon")
            if "lon" in candidate
            else candidate.get("lng")
            if "lng" in candidate
            else candidate.get("long")
            if "long" in candidate
            else candidate.get("longitude")
        )
        if latitude is not None and longitude is not None:
            return True
    return False


def public_site_lookup(dive_sites: list[dict]) -> dict[str, dict]:
    lookup: dict[str, dict] = {}
    for site in dive_sites:
        name = clean_profile_text((site or {}).get("name")).lower()
        latitude = clean_coordinate_value((site or {}).get("latitude"))
        longitude = clean_coordinate_value((site or {}).get("longitude"))
        if not name or latitude is None or longitude is None:
            continue
        lookup[name] = {
            "lat": latitude,
            "lon": longitude,
        }
    return lookup


def enrich_public_dive(dive: dict, site_lookup: dict[str, dict]) -> dict:
    payload = dict(dive)
    if public_dive_has_coordinates(payload):
        return payload
    logbook = (payload.get("fields") or {}).get("logbook")
    site_name = clean_profile_text((logbook or {}).get("site")).lower() if isinstance(logbook, dict) else ""
    coordinates = site_lookup.get(site_name)
    if coordinates:
        payload["location"] = coordinates
    return payload


def get_public_profile_dives(conn: psycopg.Connection, public_slug: str) -> tuple[dict | None, list[dict], dict]:
    normalized_slug = normalize_public_slug(public_slug)
    if not normalized_slug:
        return None, [], {}

    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT *
            FROM user_profile
            WHERE public_slug=%s AND public_dives_enabled=TRUE
            """,
            (normalized_slug,),
        )
        profile_row = cur.fetchone()
    if not profile_row:
        return None, [], {}

    user_id = clean_profile_text(profile_row.get("user_id"))
    _, dive_sites, _, _ = resolve_user_profile_collections(conn, user_id, profile_row)
    site_lookup = public_site_lookup(dive_sites)
    dives = [
        enrich_public_dive(dive, site_lookup)
        for dive in list_all_dives(conn, user_id, include_samples=True, include_raw_data=False)
        if is_logbook_complete((dive.get("fields") or {}).get("logbook"))
    ]
    return public_profile_payload(profile_row), dives, summarize_dives(dives)


def summarize_dives(dives: list[dict], total_count: int | None = None) -> dict:
    def pressure_range(dive: dict) -> tuple[float | None, float | None]:
        tanks = dive.get("fields", {}).get("tanks") if isinstance(dive.get("fields"), dict) else []
        primary_tank = tanks[0] if isinstance(tanks, list) and tanks else {}
        if isinstance(primary_tank, dict):
            begin = primary_tank.get("beginpressure_bar")
            end = primary_tank.get("endpressure_bar")
            if isinstance(begin, (int, float)) and isinstance(end, (int, float)):
                return float(begin), float(end)

        pressures: list[float] = []
        for sample in dive.get("samples") or []:
            tank_pressure = sample.get("tank_pressure_bar") if isinstance(sample, dict) else None
            if isinstance(tank_pressure, dict):
                numeric_values = [value for value in tank_pressure.values() if isinstance(value, (int, float))]
                if numeric_values:
                    pressures.append(float(numeric_values[0]))
        if not pressures:
            return None, None
        return max(pressures), min(pressures)

    total_dives = int(total_count if total_count is not None else len(dives))
    total_seconds = sum(int(resolve_duration_seconds(dive) or 0) for dive in dives)
    max_depth = max((float(dive.get("max_depth_m") or 0) for dive in dives), default=0.0)
    total_bar_consumed = 0
    for dive in dives:
        begin, end = pressure_range(dive)
        if begin is None or end is None:
            continue
        total_bar_consumed += max(0, round(begin - end))
    average_duration_seconds = round(total_seconds / total_dives, 2) if total_dives else 0
    average_max_depth_m = (
        round(
            sum(float(dive.get("max_depth_m") or 0) for dive in dives) / total_dives,
            2,
        )
        if total_dives
        else 0
    )
    total_hours = round(total_seconds / 3600, 1) if total_seconds else 0

    return {
        "totalDives": total_dives,
        "totalSeconds": total_seconds,
        "totalHours": total_hours,
        "maxDepth": max_depth,
        "totalBarConsumed": total_bar_consumed,
        "averageDurationSeconds": average_duration_seconds,
        "averageMaxDepth": average_max_depth_m,
        "bottomTimeProgress": min(100, round(total_hours)),
    }


def get_dive(conn: psycopg.Connection, user_id: str, dive_id: int, include_raw_data: bool) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM dives WHERE user_id=%s AND id=%s", (user_id, dive_id))
        row = cur.fetchone()
    return decode_dive_row(row, include_samples=True, include_raw_data=include_raw_data) if row else None


def empty_user_profile() -> dict:
    return {
        "name": "",
        "email": "",
        "public_dives_enabled": False,
        "public_slug": "",
        "licenses": [],
        "dive_sites": [],
        "buddies": [],
        "guides": [],
        "updated_at": None,
    }


def public_profile_payload(row: dict | None) -> dict:
    source = row or {}
    return {
        "name": clean_profile_text(source.get("name")) or "DiveVault Diver",
        "public_slug": clean_profile_text(source.get("public_slug")),
    }


def decode_user_profile_row(
    row: dict | None,
    license_documents: dict[str, dict] | None = None,
    *,
    licenses: list[dict] | None = None,
    dive_sites: list[dict] | None = None,
    buddies: list[dict] | None = None,
    guides: list[dict] | None = None,
) -> dict:
    if not row:
        return empty_user_profile()

    license_documents = license_documents or {}
    normalized_licenses = normalize_profile_licenses(licenses or [])

    hydrated_licenses = []
    for license_entry in normalized_licenses:
        pdf_summary = license_documents.get(license_entry["id"])
        hydrated_licenses.append({
            **license_entry,
            "pdf": pdf_summary,
        })

    normalized_dive_sites = normalize_profile_dive_sites(dive_sites or [])
    normalized_buddies = normalize_profile_buddies(buddies or [])
    normalized_guides = normalize_profile_guides(guides or [])

    payload = {
        "name": clean_profile_text(row.get("name")),
        "email": clean_profile_text(row.get("email")),
        "public_dives_enabled": clean_profile_bool(row.get("public_dives_enabled")),
        "public_slug": clean_profile_text(row.get("public_slug")),
        "licenses": hydrated_licenses,
        "dive_sites": normalized_dive_sites,
        "buddies": normalized_buddies,
        "guides": normalized_guides,
        "updated_at": row.get("updated_at"),
    }

    return payload


def get_user_profile_license_document_summaries(conn: psycopg.Connection, user_id: str) -> dict[str, dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT license_id, filename, content_type, pdf_data, uploaded_at
            FROM user_profile_license_documents
            WHERE user_id=%s
            """,
            (user_id,),
        )
        rows = cur.fetchall()

    return {
        row["license_id"]: profile_license_document_summary(
            license_id=row["license_id"],
            filename=row["filename"],
            content_type=row["content_type"],
            data=row["pdf_data"],
            uploaded_at=row.get("uploaded_at"),
        )
        for row in rows
    }


def get_user_profile(conn: psycopg.Connection, user_id: str) -> dict:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM user_profile WHERE user_id=%s", (user_id,))
        row = cur.fetchone()
    licenses, dive_sites, buddies, guides = resolve_user_profile_collections(conn, user_id, row)
    return decode_user_profile_row(
        row,
        get_user_profile_license_document_summaries(conn, user_id),
        licenses=licenses,
        dive_sites=dive_sites,
        buddies=buddies,
        guides=guides,
    )


def save_user_profile(conn: psycopg.Connection, user_id: str, payload: dict | None) -> dict:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM user_profile WHERE user_id=%s", (user_id,))
        row = cur.fetchone()

        existing = row or {}
        source = payload if isinstance(payload, dict) else {}
        updated_at = now_iso()
        existing_name = clean_profile_text(existing.get("name"))
        existing_email = clean_profile_text(existing.get("email"))
        existing_public_dives_enabled = clean_profile_bool(existing.get("public_dives_enabled"))
        existing_public_slug = clean_profile_text(existing.get("public_slug"))
        existing_licenses, existing_dive_sites, existing_buddies, existing_guides = resolve_user_profile_collections(
            conn, user_id, existing
        )
        licenses = normalize_profile_licenses(source.get("licenses")) if "licenses" in source else existing_licenses
        dive_sites = normalize_profile_dive_sites(source.get("dive_sites")) if "dive_sites" in source else existing_dive_sites
        buddies = normalize_profile_buddies(source.get("buddies")) if "buddies" in source else existing_buddies
        guides = normalize_profile_guides(source.get("guides")) if "guides" in source else existing_guides
        public_dives_enabled = clean_profile_bool(source.get("public_dives_enabled")) if "public_dives_enabled" in source else existing_public_dives_enabled
        public_slug = existing_public_slug
        if public_dives_enabled:
            public_slug = ensure_unique_public_slug(cur, user_id, source.get("public_slug"), existing_public_slug)
        cur.execute(
            """
            INSERT INTO user_profile(
                user_id, name, email, public_dives_enabled, public_slug, updated_at
            )
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id)
            DO UPDATE SET
                name=excluded.name,
                email=excluded.email,
                public_dives_enabled=excluded.public_dives_enabled,
                public_slug=excluded.public_slug,
                updated_at=excluded.updated_at
            """,
            (
                user_id,
                clean_profile_text(source.get("name")) if "name" in source else existing_name,
                clean_profile_text(source.get("email")) if "email" in source else existing_email,
                public_dives_enabled,
                public_slug,
                updated_at,
            ),
        )
        replace_user_profile_licenses(cur, user_id, licenses)
        replace_user_profile_dive_sites(cur, user_id, dive_sites)
        replace_user_profile_buddies(cur, user_id, buddies)
        replace_user_profile_guides(cur, user_id, guides)
        if licenses:
            cur.execute(
                "DELETE FROM user_profile_license_documents WHERE user_id=%s AND license_id <> ALL(%s)",
                (user_id, [license["id"] for license in licenses]),
            )
        else:
            cur.execute("DELETE FROM user_profile_license_documents WHERE user_id=%s", (user_id,))
    conn.commit()
    return get_user_profile(conn, user_id)


def save_user_profile_license_pdf(
    conn: psycopg.Connection,
    user_id: str,
    *,
    license_id: str,
    filename: str,
    content_type: str,
    pdf_bytes: bytes,
) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM user_profile WHERE user_id=%s", (user_id,))
        row = cur.fetchone()

        existing = row or {}
        existing_licenses, existing_dive_sites, existing_buddies, existing_guides = resolve_user_profile_collections(conn, user_id, existing)
        if not any(license["id"] == license_id for license in existing_licenses):
            return None

        uploaded_at = now_iso()
        cur.execute(
            """
            INSERT INTO user_profile(
                user_id, name, email, public_dives_enabled, public_slug, updated_at
            )
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id)
            DO UPDATE SET
                name=excluded.name,
                email=excluded.email,
                public_dives_enabled=excluded.public_dives_enabled,
                public_slug=excluded.public_slug,
                updated_at=excluded.updated_at
            """,
            (
                user_id,
                clean_profile_text(existing.get("name")),
                clean_profile_text(existing.get("email")),
                clean_profile_bool(existing.get("public_dives_enabled")),
                clean_profile_text(existing.get("public_slug")),
                uploaded_at,
            ),
        )
        cur.execute(
            """
            INSERT INTO user_profile_license_documents(user_id, license_id, filename, content_type, pdf_data, uploaded_at)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, license_id)
            DO UPDATE SET
                filename=excluded.filename,
                content_type=excluded.content_type,
                pdf_data=excluded.pdf_data,
                uploaded_at=excluded.uploaded_at
            """,
            (user_id, license_id, filename, content_type, pdf_bytes, uploaded_at),
        )
    conn.commit()
    return get_user_profile(conn, user_id)


def get_user_profile_license_pdf(conn: psycopg.Connection, user_id: str, license_id: str) -> dict | None:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT filename, content_type, pdf_data, uploaded_at
            FROM user_profile_license_documents
            WHERE user_id=%s AND license_id=%s
            """,
            (user_id, license_id),
        )
        row = cur.fetchone()
    if row and row.get("pdf_data") is not None:
        return {
            "filename": row.get("filename") or "diving-licenses.pdf",
            "content_type": row.get("content_type") or "application/pdf",
            "data": row.get("pdf_data"),
            "uploaded_at": row.get("uploaded_at"),
        }
    return None


def delete_dive(conn: psycopg.Connection, user_id: str, dive_id: int) -> bool:
    with conn.cursor() as cur:
        cur.execute("DELETE FROM dives WHERE user_id=%s AND id=%s RETURNING id", (user_id, dive_id))
        deleted = cur.fetchone() is not None
    conn.commit()
    return deleted


def sanitize_logbook_payload(payload: dict | None, existing_logbook: dict | None = None) -> dict:
    source = payload or {}
    if isinstance(source.get("logbook"), dict):
        source = source["logbook"]
    commit = bool((payload or {}).get("commit"))
    existing = normalize_logbook(existing_logbook)

    logbook = {
        "site": clean_logbook_text(source.get("site")),
        "buddy": clean_logbook_text(source.get("buddy")),
        "guide": clean_logbook_text(source.get("guide")),
        "notes": clean_logbook_text(source.get("notes")),
        "updated_at": now_iso(),
        "status": "imported",
    }

    if all(logbook[key] for key in LOGBOOK_REQUIRED_FIELDS) and (commit or existing.get("status") == "complete"):
        logbook["status"] = "complete"
        existing_completed_at = existing.get("completed_at") or source.get("completed_at")
        logbook["completed_at"] = existing_completed_at if isinstance(existing_completed_at, str) and existing_completed_at else now_iso()

    return logbook


def apply_tank_volume_update(fields: dict, payload: dict | None) -> dict:
    source = payload if isinstance(payload, dict) else {}
    tank_volume = clean_tank_volume_value(source.get("tank_volume_l"))
    if tank_volume is None:
        return fields

    next_fields = dict(fields)
    existing_tanks = next_fields.get("tanks")
    tanks = list(existing_tanks) if isinstance(existing_tanks, list) else []
    if tanks and isinstance(tanks[0], dict):
        primary_tank = dict(tanks[0])
        tanks[0] = primary_tank
    else:
        primary_tank = {}
        if tanks:
            tanks[0] = primary_tank
        else:
            tanks = [primary_tank]
    primary_tank["volume"] = tank_volume
    next_fields["tanks"] = tanks
    return next_fields


def update_dive_logbook(conn: psycopg.Connection, user_id: str, dive_id: int, payload: dict | None) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM dives WHERE user_id=%s AND id=%s", (user_id, dive_id))
        row = cur.fetchone()
        if not row:
            return None

        fields = row.get("fields_json") or {}
        samples = row.get("samples_json") or []
        if not isinstance(fields, dict):
            fields = json.loads(fields)
        if isinstance(samples, str):
            samples = json.loads(samples)
        fields = normalize_dive_fields(fields, samples=samples, duration_seconds=resolve_duration_seconds(row))
        fields["logbook"] = sanitize_logbook_payload(payload, fields.get("logbook"))
        fields = apply_tank_volume_update(fields, payload)

        cur.execute(
            "UPDATE dives SET fields_json=%s WHERE user_id=%s AND id=%s",
            (Jsonb(fields), user_id, dive_id),
        )
    conn.commit()
    return get_dive(conn, user_id, dive_id, include_raw_data=False)


def decode_base64_payload(payload: dict) -> bytes:
    try:
        return base64.b64decode(payload["raw_data_b64"], validate=True)
    except (ValueError, binascii.Error) as exc:
        raise ValueError("raw_data_b64 must be valid base64") from exc


def normalize_email(value: object) -> str:
    return clean_profile_text(value).strip().lower()


def _ensure_auth_instance_settings_row(cur: psycopg.Cursor) -> None:
    cur.execute(
        """
        INSERT INTO auth_instance_settings(singleton, initialized, public_registration_enabled, owner_user_id, updated_at)
        VALUES (TRUE, FALSE, FALSE, NULL, %s)
        ON CONFLICT (singleton) DO NOTHING
        """,
        (now_iso(),),
    )


def get_auth_instance_settings(conn: psycopg.Connection) -> dict:
    with conn.cursor() as cur:
        _ensure_auth_instance_settings_row(cur)
        cur.execute(
            """
            SELECT initialized, public_registration_enabled, owner_user_id, updated_at
            FROM auth_instance_settings
            WHERE singleton=TRUE
            """
        )
        row = cur.fetchone() or {}
        cur.execute("SELECT COUNT(*) AS count FROM auth_users")
        count_row = cur.fetchone() or {}
    conn.commit()
    user_count = int((count_row or {}).get("count") or 0)
    initialized = bool((row or {}).get("initialized"))
    public_registration_enabled = bool((row or {}).get("public_registration_enabled"))
    bootstrap_registration_open = (not initialized) and user_count == 0
    return {
        "initialized": initialized,
        "public_registration_enabled": public_registration_enabled,
        "owner_user_id": clean_profile_text((row or {}).get("owner_user_id")),
        "updated_at": (row or {}).get("updated_at"),
        "user_count": user_count,
        "bootstrap_registration_open": bootstrap_registration_open,
        "public_registration_open": bootstrap_registration_open or public_registration_enabled,
    }


def update_auth_instance_settings(
    conn: psycopg.Connection,
    *,
    public_registration_enabled: bool | None = None,
    initialized: bool | None = None,
    owner_user_id: str | None = None,
) -> dict:
    with conn.cursor() as cur:
        _ensure_auth_instance_settings_row(cur)
        cur.execute(
            """
            SELECT initialized, public_registration_enabled, owner_user_id
            FROM auth_instance_settings
            WHERE singleton=TRUE
            FOR UPDATE
            """
        )
        existing = cur.fetchone() or {}
        next_initialized = bool(existing.get("initialized")) if initialized is None else bool(initialized)
        next_public_registration_enabled = (
            bool(existing.get("public_registration_enabled"))
            if public_registration_enabled is None
            else bool(public_registration_enabled)
        )
        next_owner_user_id = clean_profile_text(existing.get("owner_user_id")) if owner_user_id is None else clean_profile_text(owner_user_id)
        cur.execute(
            """
            UPDATE auth_instance_settings
            SET initialized=%s,
                public_registration_enabled=%s,
                owner_user_id=%s,
                updated_at=%s
            WHERE singleton=TRUE
            """,
            (next_initialized, next_public_registration_enabled, next_owner_user_id or None, now_iso()),
        )
    conn.commit()
    return get_auth_instance_settings(conn)


def create_bootstrap_auth_user(
    conn: psycopg.Connection,
    *,
    user_id: str,
    email: str,
    password_hash: str,
    first_name: str,
    last_name: str,
) -> dict:
    normalized_email = normalize_email(email)
    now_value = now_iso()
    with conn.cursor() as cur:
        _ensure_auth_instance_settings_row(cur)
        cur.execute(
            """
            SELECT initialized, owner_user_id
            FROM auth_instance_settings
            WHERE singleton=TRUE
            FOR UPDATE
            """
        )
        settings = cur.fetchone() or {}
        cur.execute("SELECT COUNT(*) AS count FROM auth_users")
        count_row = cur.fetchone() or {}
        user_count = int((count_row or {}).get("count") or 0)
        if bool(settings.get("initialized")) or user_count > 0:
            raise ValueError("Public registration is closed")
        cur.execute("SELECT 1 FROM auth_users WHERE LOWER(email)=LOWER(%s)", (normalized_email,))
        if cur.fetchone():
            raise ValueError("Email already registered")
        cur.execute(
            """
            INSERT INTO auth_users(id, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at, last_login_at)
            VALUES (%s, %s, %s, %s, %s, 'admin', TRUE, %s, %s, NULL)
            """,
            (
                clean_profile_text(user_id),
                normalized_email,
                clean_profile_text(password_hash),
                clean_profile_text(first_name),
                clean_profile_text(last_name),
                now_value,
                now_value,
            ),
        )
        cur.execute(
            """
            UPDATE auth_instance_settings
            SET initialized=TRUE,
                owner_user_id=%s,
                updated_at=%s
            WHERE singleton=TRUE
            """,
            (clean_profile_text(user_id), now_iso()),
        )
    conn.commit()
    return get_auth_user_by_id(conn, user_id) or {}


def cleanup_auth_invites_with_cursor(cur: psycopg.Cursor, now_timestamp: int) -> None:
    cur.execute(
        """
        DELETE FROM auth_user_invites
        WHERE accepted_at IS NOT NULL OR expires_at <= %s
        """,
        (int(now_timestamp),),
    )


def create_auth_invite(
    conn: psycopg.Connection,
    *,
    token: str,
    email: str,
    first_name: str,
    last_name: str,
    role: str,
    invited_by_user_id: str,
    expires_at: int,
    now_timestamp: int,
) -> dict:
    with conn.cursor() as cur:
        cleanup_auth_invites_with_cursor(cur, now_timestamp)
        cur.execute("DELETE FROM auth_user_invites WHERE LOWER(email)=LOWER(%s)", (normalize_email(email),))
        cur.execute(
            """
            INSERT INTO auth_user_invites(
                token, email, first_name, last_name, role, invited_by_user_id, created_at, expires_at, accepted_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, NULL)
            """,
            (
                clean_profile_text(token),
                normalize_email(email),
                clean_profile_text(first_name),
                clean_profile_text(last_name),
                clean_profile_text(role) or "user",
                clean_profile_text(invited_by_user_id),
                int(now_timestamp),
                int(expires_at),
            ),
        )
        cur.execute(
            """
            SELECT token, email, first_name, last_name, role, invited_by_user_id, created_at, expires_at
            FROM auth_user_invites
            WHERE token=%s
            """,
            (clean_profile_text(token),),
        )
        row = cur.fetchone() or {}
    conn.commit()
    return dict(row)


def get_auth_invite_by_token(conn: psycopg.Connection, token: str, *, now_timestamp: int) -> dict | None:
    with conn.cursor() as cur:
        cleanup_auth_invites_with_cursor(cur, now_timestamp)
        cur.execute(
            """
            SELECT token, email, first_name, last_name, role, invited_by_user_id, created_at, expires_at
            FROM auth_user_invites
            WHERE token=%s AND accepted_at IS NULL AND expires_at > %s
            """,
            (clean_profile_text(token), int(now_timestamp)),
        )
        row = cur.fetchone()
    conn.commit()
    return dict(row) if row else None


def create_auth_user_from_invite(
    conn: psycopg.Connection,
    *,
    invite_token: str,
    user_id: str,
    password_hash: str,
) -> dict:
    now_value = now_iso()
    now_timestamp = int(time.time())
    with conn.cursor() as cur:
        cleanup_auth_invites_with_cursor(cur, now_timestamp)
        cur.execute(
            """
            SELECT token, email, first_name, last_name, role
            FROM auth_user_invites
            WHERE token=%s AND accepted_at IS NULL AND expires_at > %s
            FOR UPDATE
            """,
            (clean_profile_text(invite_token), now_timestamp),
        )
        invite = cur.fetchone()
        if not invite:
            raise ValueError("Invitation is invalid or expired")
        invite_email = normalize_email(invite.get("email"))
        cur.execute("SELECT 1 FROM auth_users WHERE LOWER(email)=LOWER(%s)", (invite_email,))
        if cur.fetchone():
            raise ValueError("Email already registered")
        cur.execute(
            """
            INSERT INTO auth_users(id, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at, last_login_at)
            VALUES (%s, %s, %s, %s, %s, %s, TRUE, %s, %s, NULL)
            """,
            (
                clean_profile_text(user_id),
                invite_email,
                clean_profile_text(password_hash),
                clean_profile_text(invite.get("first_name")),
                clean_profile_text(invite.get("last_name")),
                clean_profile_text(invite.get("role")) or "user",
                now_value,
                now_value,
            ),
        )
        cur.execute(
            """
            UPDATE auth_user_invites
            SET accepted_at=%s
            WHERE token=%s
            """,
            (now_timestamp, clean_profile_text(invite_token)),
        )
    conn.commit()
    return get_auth_user_by_id(conn, user_id) or {}


def count_auth_users(conn: psycopg.Connection) -> int:
    with conn.cursor() as cur:
        cur.execute("SELECT COUNT(*) AS count FROM auth_users")
        row = cur.fetchone() or {}
    return int((row or {}).get("count") or 0)


def get_auth_user_by_email(conn: psycopg.Connection, email: str) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM auth_users WHERE LOWER(email)=LOWER(%s)", (normalize_email(email),))
        return cur.fetchone()


def get_auth_user_by_id(conn: psycopg.Connection, user_id: str) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM auth_users WHERE id=%s", (clean_profile_text(user_id),))
        return cur.fetchone()


def create_auth_user(conn: psycopg.Connection, *, user_id: str, email: str, password_hash: str, first_name: str, last_name: str, role: str) -> dict:
    now_value = now_iso()
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO auth_users(id, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at, last_login_at)
            VALUES (%s, %s, %s, %s, %s, %s, TRUE, %s, %s, NULL)
            """,
            (
                clean_profile_text(user_id),
                normalize_email(email),
                clean_profile_text(password_hash),
                clean_profile_text(first_name),
                clean_profile_text(last_name),
                clean_profile_text(role) or "user",
                now_value,
                now_value,
            ),
        )
    conn.commit()
    return get_auth_user_by_id(conn, user_id) or {}


def upsert_auth_user(conn: psycopg.Connection, *, user_id: str, email: str, password_hash: str, first_name: str, last_name: str, role: str, is_active: bool = True) -> dict:
    now_value = now_iso()
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO auth_users(id, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at, last_login_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, NULL)
            ON CONFLICT (id) DO UPDATE SET
                email=excluded.email,
                password_hash=excluded.password_hash,
                first_name=excluded.first_name,
                last_name=excluded.last_name,
                role=excluded.role,
                is_active=excluded.is_active,
                updated_at=excluded.updated_at
            """,
            (
                clean_profile_text(user_id),
                normalize_email(email),
                clean_profile_text(password_hash),
                clean_profile_text(first_name),
                clean_profile_text(last_name),
                clean_profile_text(role) or "user",
                bool(is_active),
                now_value,
                now_value,
            ),
        )
    conn.commit()
    return get_auth_user_by_id(conn, user_id) or {}


def update_auth_user_last_login(conn: psycopg.Connection, user_id: str) -> None:
    with conn.cursor() as cur:
        cur.execute("UPDATE auth_users SET last_login_at=%s, updated_at=%s WHERE id=%s", (now_iso(), now_iso(), clean_profile_text(user_id)))
    conn.commit()


def list_auth_users(conn: psycopg.Connection) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, email, first_name, last_name, role, is_active, created_at, updated_at, last_login_at
            FROM auth_users
            ORDER BY created_at ASC, email ASC
            """
        )
        rows = cur.fetchall() or []
    return [dict(row) for row in rows]


def update_auth_user(conn: psycopg.Connection, user_id: str, payload: dict) -> dict | None:
    existing = get_auth_user_by_id(conn, user_id)
    if not existing:
        return None
    next_email = normalize_email(payload.get("email")) if "email" in payload else existing.get("email")
    next_first_name = clean_profile_text(payload.get("first_name")) if "first_name" in payload else clean_profile_text(existing.get("first_name"))
    next_last_name = clean_profile_text(payload.get("last_name")) if "last_name" in payload else clean_profile_text(existing.get("last_name"))
    next_role = clean_profile_text(payload.get("role")) if "role" in payload else clean_profile_text(existing.get("role"))
    next_is_active = bool(payload.get("is_active")) if "is_active" in payload else bool(existing.get("is_active"))
    next_password_hash = clean_profile_text(payload.get("password_hash")) if "password_hash" in payload else clean_profile_text(existing.get("password_hash"))

    with conn.cursor() as cur:
        cur.execute(
            """
            UPDATE auth_users
            SET email=%s, first_name=%s, last_name=%s, role=%s, is_active=%s, password_hash=%s, updated_at=%s
            WHERE id=%s
            """,
            (next_email, next_first_name, next_last_name, next_role or "user", next_is_active, next_password_hash, now_iso(), clean_profile_text(user_id)),
        )
    conn.commit()
    return get_auth_user_by_id(conn, user_id)


def delete_auth_user(conn: psycopg.Connection, user_id: str) -> bool:
    with conn.cursor() as cur:
        cur.execute("DELETE FROM auth_users WHERE id=%s", (clean_profile_text(user_id),))
        deleted = cur.rowcount > 0
    conn.commit()
    return deleted
