package migrations

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/jlemmings/divevault/backend-go/internal/store"
)

const CurrentSchemaVersion = 14

const schemaSQL = `
CREATE TABLE IF NOT EXISTS device_state (
    user_id TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, vendor, product)
);

CREATE TABLE IF NOT EXISTS dives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    dive_uid TEXT NOT NULL,
    started_at TEXT,
    duration_seconds INTEGER,
    duration_ms BIGINT,
    max_depth_m DOUBLE PRECISION,
    avg_depth_m DOUBLE PRECISION,
    import_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fields_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_sha256 TEXT NOT NULL,
    raw_data BYTEA NOT NULL,
    samples_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    imported_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_profile (
    user_id TEXT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    public_dives_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_slug TEXT NOT NULL DEFAULT '',
    logbook_display_fields_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    required_logbook_fields_json JSONB NOT NULL DEFAULT '["site"]'::jsonb,
    equipment_selection_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_profile_license_documents (
    user_id TEXT NOT NULL,
    license_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    pdf_data BYTEA NOT NULL,
    uploaded_at TEXT NOT NULL,
    PRIMARY KEY (user_id, license_id)
);

CREATE TABLE IF NOT EXISTS user_profile_licenses (
    user_id TEXT NOT NULL,
    license_id TEXT NOT NULL,
    company TEXT,
    certification_name TEXT,
    student_number TEXT,
    certification_date TEXT,
    instructor_number TEXT,
    PRIMARY KEY (user_id, license_id)
);

CREATE TABLE IF NOT EXISTS user_profile_dive_sites (
    user_id TEXT NOT NULL,
    site_id TEXT NOT NULL,
    name TEXT,
    location TEXT,
    country TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    PRIMARY KEY (user_id, site_id)
);

CREATE TABLE IF NOT EXISTS user_profile_buddies (
    user_id TEXT NOT NULL,
    buddy_id TEXT NOT NULL,
    name TEXT,
    PRIMARY KEY (user_id, buddy_id)
);

CREATE TABLE IF NOT EXISTS user_profile_guides (
    user_id TEXT NOT NULL,
    guide_id TEXT NOT NULL,
    name TEXT,
    PRIMARY KEY (user_id, guide_id)
);

CREATE TABLE IF NOT EXISTS cli_sync_auth_requests (
    code TEXT PRIMARY KEY,
    status TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    approved_at BIGINT,
    token TEXT UNIQUE,
    token_expires_at BIGINT,
    user_id TEXT,
    email TEXT,
    session_id TEXT
);

CREATE TABLE IF NOT EXISTS auth_users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_login_at TEXT
);

CREATE TABLE IF NOT EXISTS auth_instance_settings (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    initialized BOOLEAN NOT NULL DEFAULT FALSE,
    public_registration_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    owner_user_id TEXT,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_user_invites (
    token TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'user',
    invited_by_user_id TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    accepted_at BIGINT
);

CREATE TABLE IF NOT EXISTS user_equipment (
    user_id TEXT NOT NULL,
    equipment_id TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT '',
    icon TEXT NOT NULL DEFAULT '',
    type TEXT NOT NULL DEFAULT '',
    year_bought INTEGER,
    vendor TEXT NOT NULL DEFAULT '',
    brand TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    serial TEXT NOT NULL DEFAULT '',
    warranty TEXT NOT NULL DEFAULT '',
    next_service_due TEXT NOT NULL DEFAULT '',
    service_interval_months INTEGER,
    last_service_date TEXT NOT NULL DEFAULT '',
    max_dives_before_service INTEGER,
    track_service BOOLEAN NOT NULL DEFAULT TRUE,
    service_tag TEXT NOT NULL DEFAULT '',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_standard BOOLEAN NOT NULL DEFAULT FALSE,
    last_serviced_at TEXT,
    last_service_dive_count INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, equipment_id)
);
`

const schemaVersionSQL = `
CREATE TABLE IF NOT EXISTS app_schema_version (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    version INTEGER NOT NULL,
    updated_at TEXT NOT NULL
);
`

type migration struct {
	version int
	sql     string
	fn      func(context.Context, pgx.Tx) error
}

func Migrate(ctx context.Context, db *store.DB) (int, error) {
	if db == nil || db.Pool() == nil {
		return 0, errors.New("database is not configured")
	}
	tx, err := db.Pool().Begin(ctx)
	if err != nil {
		return 0, err
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, schemaSQL); err != nil {
		return 0, err
	}
	version, err := schemaVersion(ctx, tx)
	if err != nil {
		return 0, err
	}
	for _, migration := range migrations() {
		if version >= migration.version {
			continue
		}
		if migration.sql != "" {
			if _, err := tx.Exec(ctx, migration.sql); err != nil {
				return version, fmt.Errorf("apply migration v%d: %w", migration.version, err)
			}
		}
		if migration.fn != nil {
			if err := migration.fn(ctx, tx); err != nil {
				return version, fmt.Errorf("apply migration v%d: %w", migration.version, err)
			}
		}
		if err := setSchemaVersion(ctx, tx, migration.version); err != nil {
			return version, err
		}
		version = migration.version
	}
	if err := tx.Commit(ctx); err != nil {
		return version, err
	}
	return version, nil
}

func SchemaVersion(ctx context.Context, db *store.DB) (int, error) {
	if db == nil || db.Pool() == nil {
		return 0, errors.New("database is not configured")
	}
	tx, err := db.Pool().Begin(ctx)
	if err != nil {
		return 0, err
	}
	defer tx.Rollback(ctx)
	version, err := schemaVersion(ctx, tx)
	if err != nil {
		return 0, err
	}
	return version, tx.Commit(ctx)
}

func schemaVersion(ctx context.Context, tx pgx.Tx) (int, error) {
	if _, err := tx.Exec(ctx, schemaVersionSQL); err != nil {
		return 0, err
	}
	if _, err := tx.Exec(ctx, `
        INSERT INTO app_schema_version(singleton, version, updated_at)
        VALUES (TRUE, 0, $1)
        ON CONFLICT (singleton) DO NOTHING
    `, nowISO()); err != nil {
		return 0, err
	}
	var version int
	if err := tx.QueryRow(ctx, "SELECT version FROM app_schema_version WHERE singleton=TRUE").Scan(&version); err != nil {
		return 0, err
	}
	return version, nil
}

func setSchemaVersion(ctx context.Context, tx pgx.Tx, version int) error {
	_, err := tx.Exec(ctx, "UPDATE app_schema_version SET version=$1, updated_at=$2 WHERE singleton=TRUE", version, nowISO())
	return err
}

func migrations() []migration {
	return []migration{
		{version: 1, sql: migrationV1SQL},
		{version: 2, fn: migrationV2},
		{version: 3, sql: migrationV3SQL},
		{version: 4, sql: migrationV4SQL},
		{version: 5, sql: migrationV5SQL},
		{version: 6, sql: migrationV6SQL},
		{version: 7, fn: migrationV7},
		{version: 8, sql: `ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS logbook_display_fields_json JSONB NOT NULL DEFAULT '[]'::jsonb;
UPDATE user_profile SET logbook_display_fields_json='[]'::jsonb WHERE logbook_display_fields_json IS NULL;`},
		{version: 9, sql: migrationV9SQL},
		{version: 10, sql: migrationV10SQL},
		{version: 11, sql: `ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS equipment_selection_enabled BOOLEAN NOT NULL DEFAULT TRUE;
UPDATE user_profile SET equipment_selection_enabled=TRUE WHERE equipment_selection_enabled IS NULL;`},
		{version: 12, sql: `ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS track_service BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS service_tag TEXT NOT NULL DEFAULT '';
UPDATE user_equipment SET track_service=TRUE WHERE track_service IS NULL;
UPDATE user_equipment SET service_tag='' WHERE service_tag IS NULL;`},
		{version: 13, sql: `ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS required_logbook_fields_json JSONB NOT NULL DEFAULT '["site"]'::jsonb;
UPDATE user_profile SET required_logbook_fields_json='["site"]'::jsonb WHERE required_logbook_fields_json IS NULL;`},
		{version: 14, sql: `ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS icon TEXT NOT NULL DEFAULT '';
UPDATE user_equipment SET icon='' WHERE icon IS NULL;`},
	}
}

func migrationV2(ctx context.Context, tx pgx.Tx) error {
	_, err := tx.Exec(ctx, `
        UPDATE dives
        SET fields_json = jsonb_set(COALESCE(fields_json, '{}'::jsonb), '{tanks}', '[{"volume": 12.0}]'::jsonb, true)
        WHERE NOT (COALESCE(fields_json, '{}'::jsonb) #> '{tanks,0}' ? 'volume')
    `)
	return err
}

func migrationV7(ctx context.Context, tx pgx.Tx) error {
	if _, err := tx.Exec(ctx, migrationV7SQL); err != nil {
		return err
	}
	var ownerUserID *string
	err := tx.QueryRow(ctx, "SELECT id FROM auth_users ORDER BY created_at ASC, email ASC LIMIT 1").Scan(&ownerUserID)
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return err
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return nil
	}
	if ownerUserID != nil && *ownerUserID != "" {
		_, err = tx.Exec(ctx, `
            UPDATE auth_instance_settings
            SET initialized=TRUE, owner_user_id=COALESCE(owner_user_id, $1), updated_at=$2
            WHERE singleton=TRUE
        `, *ownerUserID, nowISO())
	}
	return err
}

func nowISO() string {
	return time.Now().UTC().Format(time.RFC3339Nano)
}

const migrationV1SQL = `
ALTER TABLE device_state ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE dives ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE dives ADD COLUMN IF NOT EXISTS duration_ms BIGINT;
ALTER TABLE dives ADD COLUMN IF NOT EXISTS import_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE dives ADD COLUMN IF NOT EXISTS fields_json JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE dives ADD COLUMN IF NOT EXISTS samples_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS public_dives_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS public_slug TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS licenses_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS dive_sites_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS buddies_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS guides_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS certification TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS registry TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_company TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_certification_name TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_student_number TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_certification_date TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_instructor_number TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_name TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_content_type TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_data BYTEA;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS license_pdf_uploaded_at TEXT;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS updated_at TEXT;
UPDATE device_state SET user_id='legacy' WHERE user_id IS NULL;
UPDATE dives SET user_id='legacy' WHERE user_id IS NULL;
UPDATE user_profile SET public_dives_enabled=FALSE WHERE public_dives_enabled IS NULL;
UPDATE user_profile SET updated_at=NOW()::text WHERE updated_at IS NULL;
UPDATE dives SET duration_ms = duration_seconds::bigint * 1000 WHERE duration_ms IS NULL AND duration_seconds IS NOT NULL;
UPDATE dives SET duration_seconds = NULL WHERE duration_ms IS NOT NULL;
ALTER TABLE device_state ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE dives ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE user_profile ALTER COLUMN public_dives_enabled SET NOT NULL;
ALTER TABLE user_profile ALTER COLUMN updated_at SET NOT NULL;
DROP INDEX IF EXISTS idx_dives_started_at;
CREATE UNIQUE INDEX IF NOT EXISTS idx_dives_user_dive_uid ON dives (user_id, dive_uid);
CREATE INDEX IF NOT EXISTS idx_dives_user_started_at ON dives (user_id, started_at DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profile_public_slug ON user_profile (public_slug) WHERE NULLIF(BTRIM(COALESCE(public_slug, '')), '') IS NOT NULL;
ALTER TABLE user_profile_guides DROP COLUMN IF EXISTS sort_order;
DROP INDEX IF EXISTS idx_user_profile_guides_user_sort;
CREATE INDEX IF NOT EXISTS idx_user_profile_guides_user_name ON user_profile_guides (user_id, LOWER(name), name, guide_id);
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS created_at BIGINT;
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS expires_at BIGINT;
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS approved_at BIGINT;
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS token TEXT;
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS token_expires_at BIGINT;
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE cli_sync_auth_requests ADD COLUMN IF NOT EXISTS session_id TEXT;
CREATE INDEX IF NOT EXISTS idx_cli_sync_auth_requests_expires_at ON cli_sync_auth_requests (expires_at);
CREATE INDEX IF NOT EXISTS idx_cli_sync_auth_requests_token_expires_at ON cli_sync_auth_requests (token_expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cli_sync_auth_requests_token ON cli_sync_auth_requests (token) WHERE token IS NOT NULL;
`

const migrationV3SQL = `
ALTER TABLE user_profile DROP COLUMN IF EXISTS licenses_json;
ALTER TABLE user_profile DROP COLUMN IF EXISTS dive_sites_json;
ALTER TABLE user_profile DROP COLUMN IF EXISTS buddies_json;
ALTER TABLE user_profile DROP COLUMN IF EXISTS guides_json;
ALTER TABLE user_profile DROP COLUMN IF EXISTS certification;
ALTER TABLE user_profile DROP COLUMN IF EXISTS registry;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_company;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_certification_name;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_student_number;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_certification_date;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_instructor_number;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_pdf_name;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_pdf_content_type;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_pdf_data;
ALTER TABLE user_profile DROP COLUMN IF EXISTS license_pdf_uploaded_at;
`

const migrationV4SQL = `
UPDATE user_profile SET name='' WHERE name IS NULL;
UPDATE user_profile SET email='' WHERE email IS NULL;
UPDATE user_profile SET public_slug='' WHERE public_slug IS NULL;
ALTER TABLE user_profile ALTER COLUMN name SET DEFAULT '';
ALTER TABLE user_profile ALTER COLUMN email SET DEFAULT '';
ALTER TABLE user_profile ALTER COLUMN public_slug SET DEFAULT '';
ALTER TABLE user_profile ALTER COLUMN name SET NOT NULL;
ALTER TABLE user_profile ALTER COLUMN email SET NOT NULL;
ALTER TABLE user_profile ALTER COLUMN public_slug SET NOT NULL;
DROP INDEX IF EXISTS idx_user_profile_public_slug;
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profile_public_slug ON user_profile (public_slug) WHERE BTRIM(public_slug) <> '';
`

const migrationV5SQL = `
DROP INDEX IF EXISTS idx_user_profile_licenses_user_sort;
DROP INDEX IF EXISTS idx_user_profile_dive_sites_user_sort;
DROP INDEX IF EXISTS idx_user_profile_buddies_user_sort;
ALTER TABLE user_profile_licenses DROP COLUMN IF EXISTS sort_order;
ALTER TABLE user_profile_dive_sites DROP COLUMN IF EXISTS sort_order;
ALTER TABLE user_profile_buddies DROP COLUMN IF EXISTS sort_order;
`

const migrationV6SQL = `
CREATE TABLE IF NOT EXISTS auth_users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_login_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_auth_users_email ON auth_users (LOWER(email));
`

const migrationV7SQL = `
CREATE TABLE IF NOT EXISTS auth_instance_settings (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    initialized BOOLEAN NOT NULL DEFAULT FALSE,
    public_registration_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    owner_user_id TEXT,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS auth_user_invites (
    token TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'user',
    invited_by_user_id TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    accepted_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_auth_user_invites_expires_at ON auth_user_invites (expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_user_invites_email ON auth_user_invites (LOWER(email));
INSERT INTO auth_instance_settings(singleton, initialized, public_registration_enabled, owner_user_id, updated_at)
VALUES (TRUE, FALSE, FALSE, NULL, NOW()::text)
ON CONFLICT (singleton) DO NOTHING;
`

const migrationV9SQL = `
CREATE TABLE IF NOT EXISTS user_equipment (
    user_id TEXT NOT NULL,
    equipment_id TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT '',
    icon TEXT NOT NULL DEFAULT '',
    type TEXT NOT NULL DEFAULT '',
    year_bought INTEGER,
    vendor TEXT NOT NULL DEFAULT '',
    brand TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    serial TEXT NOT NULL DEFAULT '',
    warranty TEXT NOT NULL DEFAULT '',
    next_service_due TEXT NOT NULL DEFAULT '',
    service_interval_months INTEGER,
    last_service_date TEXT NOT NULL DEFAULT '',
    max_dives_before_service INTEGER,
    track_service BOOLEAN NOT NULL DEFAULT TRUE,
    service_tag TEXT NOT NULL DEFAULT '',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_standard BOOLEAN NOT NULL DEFAULT FALSE,
    last_serviced_at TEXT,
    last_service_dive_count INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, equipment_id)
);
`

const migrationV10SQL = `
ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS model TEXT NOT NULL DEFAULT '';
ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS serial TEXT NOT NULL DEFAULT '';
ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS service_interval_months INTEGER;
ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS last_service_date TEXT NOT NULL DEFAULT '';
ALTER TABLE user_equipment ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE user_equipment SET category=type WHERE category='' AND type<>'';
UPDATE user_equipment SET name=BTRIM(CONCAT_WS(' ', NULLIF(brand, ''), NULLIF(type, ''))) WHERE name='';
UPDATE user_equipment SET is_default=is_standard WHERE is_default=FALSE AND is_standard=TRUE;
`
